- chart-values/elasticsearch_values.yaml
- chart-values/grafana_values.yaml
- chart-values/kibana_values.yaml
- chart-values/oauth2-proxy_values.yaml
- chart-values/prometheus_values.yaml
- terraform/aws/environments/dev/cluster-post-installation/main.tf
- terraform/aws/environments/dev/cluster-post-installation/variables.tf
- terraform/aws/environments/dev/cluster/main.tf
- terraform/aws/environments/dev/cluster/variables.tf
- terraform/aws/environments/test/cluster-post-installation/main.tf
- terraform/aws/environments/test/cluster-post-installation/variables.tf
- terraform/aws/environments/test/cluster/main.tf
- terraform/aws/environments/test/cluster/output.tf
- terraform/aws/environments/test/cluster/variables.tf
- terraform/aws/modules/cluster-post-installation/oauth2.tf
- terraform/aws/modules/cluster-post-installation/variables.tf
- terraform/aws/modules/cluster/master.tf
- terraform/aws/modules/cluster/master_sg.tf
- terraform/aws/modules/cluster/variables.tf
- terraform/aws/modules/cluster/worker_asg.tf
Jira Ticket -> https://mattermost.atlassian.net/browse/MM-15638
- Github authentication using oauth2 added for:
- Kibana
- Grafana
- Prometheus
- Code cleanup
> MM-15638 Adding authentication for monitoring apps and general code improvememts

- chart-values/nginx-internal_values.yaml
- terraform/aws/modules/cluster-post-installation/ingress-internal.tf
Adding nginx-internal which will be used by Provisioner server.
> MM-15511 adding internal nginx for central monitoring cluster

- terraform/aws/environments/dev/cluster-post-installation/variables.tf
- terraform/aws/environments/dev/cluster/variables.tf
- terraform/aws/environments/test/cluster-post-installation/variables.tf
- terraform/aws/environments/test/cluster/variables.tf
JIRA: https://mattermost.atlassian.net/browse/MM-16414
> rename cloud-monitoring to cloud-command-control

- terraform/aws/environments/staging/cluster-post-installation/main.tf
- terraform/aws/environments/staging/cluster-post-installation/variables.tf
- terraform/aws/environments/staging/cluster/main.tf
- terraform/aws/environments/staging/cluster/output.tf
- terraform/aws/environments/staging/cluster/variables.tf
- terraform/aws/environments/staging/route53-registration/main.tf
- terraform/aws/environments/staging/route53-registration/variables.tf
- terraform/aws/modules/cluster-post-installation/dashboard.tf
This PR adds the staging env for the cloud monitoring/provisioner
> add staging environment

- prometheus-dns-registration-service/.gitignore
- prometheus-dns-registration-service/main.go
- terraform/aws/modules/cluster/worker_asg.tf
- terraform/aws/modules/route53-registration/route53.tf
just to sync the repo, everything is already applied
> Update several things

- terraform/aws/environments/staging/cluster/main.tf
- terraform/aws/environments/test/cluster/main.tf
- terraform/aws/modules/cluster/grafana-aws-metrics.tf
- terraform/aws/modules/cluster/variables.tf
- terraform/aws/modules/cluster/worker_iam.tf
This PR automates the deployment and setup of Grafana-Metrics-Lambda function.
> MM-19082-terraform Automation of grafana-aws-metrics lambda deployment

- terraform/aws/environments/dev/security/main.tf
- terraform/aws/environments/dev/security/variables.tf
- terraform/aws/environments/staging/security/main.tf
- terraform/aws/environments/staging/security/variables.tf
- terraform/aws/environments/test/security/main.tf
- terraform/aws/environments/test/security/variables.tf
- terraform/aws/modules/security/variables.tf
- terraform/aws/modules/security/vpc_flow_logs.tf
This PR adds the terraform template code to automatically set up VPC flow logs in each account.
> MM-19645 Adding terraform templates for VPC flow logs setup

- terraform/aws/modules/subnet-and-networking/route_tables.tf
> MM-21186 Addind a transit gateway route for public subnets to enable access to private elbs

- terraform/aws/modules/cluster-post-installation/provisioner.tf
- Remove the PV from the provisioner per https://github.com/mattermost/mattermost-cloud/pull/123
- update the deployment for the provisioner installation to add an extra label to not conflict with the main deployment
> remove PVC and update label for the provisioner installation

- terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf
adding missing permissions
TODO:
will do tomorrow
> Add new permissions

- terraform/aws/modules/cluster-post-installation/provisioner.tf
follow up of https://github.com/mattermost/mattermost-cloud/pull/125 to remove the flags from the deployment
> remove deprecated flags

- terraform/aws/environments/prod/4-command-and-control/3-cluster-post-installation/main.tf
- terraform/aws/environments/staging/4-command-and-control/3-cluster-post-installation/main.tf
- terraform/aws/environments/test/4-command-and-control/3-cluster-post-installation/main.tf
- terraform/aws/modules/cluster-post-installation/variables.tf
> update terraform for provisioner

- terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf
- Adds Rds Policy to be able to delete RDS instances
note: need to apply o stg/prod
> Add RDS policy

- terraform/aws/environments/prod/4-command-and-control/1-cluster/main.tf
- terraform/aws/environments/staging/4-command-and-control/1-cluster/main.tf
- terraform/aws/environments/test/4-command-and-control/1-cluster/main.tf
- terraform/aws/modules/cluster/aws_auth_configmap.tf
- terraform/aws/modules/cluster/cloud-server-auth.tf
- terraform/aws/modules/cluster/dev_access_iam.tf
- terraform/aws/modules/cluster/grafana-aws-metrics.tf
> MM-21841 Adding role for developer access to C&C cluster

- terraform/aws/environments/core/3-security/main.tf
- terraform/aws/environments/core/3-security/variables.tf
Adding security module for core account to enable VPC flow logs
> Adding security module for core account to enable VPC flow logs

- prometheus-dns-registration-service/main.go
final fix, tested on test env and now it is working
> fix configmap struct

- terraform/aws/modules/subnet-and-networking/provisioner_db_parameter_group.tf
Adding DB Parameter Groups for DB migrations
> MM-21944 Adding DB Parameter Groups for DB migrations

- terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf
while deleting a cluster in STG notice it got permission denied to list the roles
note: need to apply on test/prod
> add missing permission

- grafana-dashboards/uptime_view.json
Adding another panel for uptime and fixing measurement
> Adding another panel for uptime and fixing measurement

- terraform/aws/modules/cluster-post-installation/provisioner-db.tf
Add the cloud vpn to the CEC AWS SG
not applied, let me know if you want this here
> add cloud vpn to the CEC AWS SG

- terraform/aws/environments/core/5-gitlab/main.tf
- terraform/aws/environments/core/5-gitlab/variables.tf
- terraform/aws/modules/eks-cluster/aws_auth_configmap.tf
- terraform/aws/modules/eks-cluster/dev_access_iam.tf
- terraform/aws/modules/eks-cluster/kubeconfig.tf
- terraform/aws/modules/eks-cluster/master.tf
- terraform/aws/modules/eks-cluster/master_iam.tf
- terraform/aws/modules/eks-cluster/master_sg.tf
- terraform/aws/modules/eks-cluster/output.tf
- terraform/aws/modules/eks-cluster/providers.tf
- terraform/aws/modules/eks-cluster/templates/kubeconfig.tpl
- terraform/aws/modules/eks-cluster/tiller.tf
- terraform/aws/modules/eks-cluster/variables.tf
- terraform/aws/modules/eks-cluster/worker_asg.tf
- terraform/aws/modules/eks-cluster/worker_iam.tf
- terraform/aws/modules/eks-cluster/worker_ingress.tf
- terraform/aws/modules/eks-cluster/worker_sg.tf
- terraform/aws/modules/gitlab/README.md
- terraform/aws/modules/gitlab/chart_values.yaml
- terraform/aws/modules/gitlab/gitlab-db.tf
- terraform/aws/modules/gitlab/gitlab-route53.tf
- terraform/aws/modules/gitlab/gitlab.tf
- terraform/aws/modules/gitlab/gitlab_cert.tf
- terraform/aws/modules/gitlab/providers.tf
- terraform/aws/modules/gitlab/s3.tf
- terraform/aws/modules/gitlab/secrets.tf
- terraform/aws/modules/gitlab/variables.tf
- Αdding Gitlab module
- Adding EKS module
- Adding Terraform configuration for Gitlab setup
> MM-22281 Adding gitlab and eks modules, gitlab deployment configuration

- chart-values/blackbox_values.yaml
- chart-values/elasticsearch-curator_values.yaml
- chart-values/flux_values.yaml
- terraform/aws/environments/prod/4-command-and-control/3-cluster-post-installation/main.tf
- terraform/aws/environments/prod/4-command-and-control/3-cluster-post-installation/variables.tf
- terraform/aws/environments/staging/4-command-and-control/3-cluster-post-installation/main.tf
- terraform/aws/environments/staging/4-command-and-control/3-cluster-post-installation/variables.tf
- terraform/aws/environments/test/4-command-and-control/3-cluster-post-installation/main.tf
- terraform/aws/environments/test/4-command-and-control/3-cluster-post-installation/variables.tf
- terraform/aws/modules/cluster-post-installation/flux.tf
- terraform/aws/modules/cluster-post-installation/variables.tf
This PR is adding support for Flux notifications.
It refers to updates to the Provisioner components and notifies in the community respective channels.
> Mm 22718 - Adding support for Flux notifications

- terraform/aws/environments/prod/4-command-and-control/1-cluster/main.tf
- terraform/aws/environments/prod/4-command-and-control/1-cluster/variables.tf
- terraform/aws/environments/staging/4-command-and-control/1-cluster/main.tf
- terraform/aws/environments/staging/4-command-and-control/1-cluster/variables.tf
- terraform/aws/environments/test/4-command-and-control/1-cluster/main.tf
- terraform/aws/environments/test/4-command-and-control/1-cluster/variables.tf
- terraform/aws/modules/cluster/elb-cloudwatch-alarms.tf
- terraform/aws/modules/cluster/variables.tf
Remove mattermost_hook which is the same as community_webhook
> remove duplicate variable

- terraform/aws/environments/core/5-gitlab/main.tf
- terraform/aws/environments/core/5-gitlab/variables.tf
- terraform/aws/modules/gitlab/chart_values.yaml
- terraform/aws/modules/gitlab/gitlab.tf
- terraform/aws/modules/gitlab/variables.tf
> Fixing SMTP 

- terraform/aws/modules/cluster-post-installation/flux.tf
Changing the url of the Flux helm release crds
> Updating helm release crd url

- terraform/aws/environments/prod/4-command-and-control/3-cluster-post-installation/main.tf
- terraform/aws/environments/prod/4-command-and-control/3-cluster-post-installation/variables.tf
- terraform/aws/environments/staging/4-command-and-control/3-cluster-post-installation/main.tf
- terraform/aws/environments/staging/4-command-and-control/3-cluster-post-installation/variables.tf
- terraform/aws/environments/staging/4-command-and-control/4-route53-registration/variables.tf
- terraform/aws/environments/test/4-command-and-control/1-cluster/variables.tf
- terraform/aws/environments/test/4-command-and-control/3-cluster-post-installation/main.tf
- terraform/aws/environments/test/4-command-and-control/3-cluster-post-installation/variables.tf
- terraform/aws/modules/cluster-post-installation/certs.tf
- terraform/aws/modules/cluster-post-installation/ingress-internal.tf
- terraform/aws/modules/cluster-post-installation/variables.tf
Update terraform to accommodate AWS ACM certificates and discard custom-made certificates/variables
https://mattermost.atlassian.net/browse/MM-22902
> Removal of self-signed certificates, usage of AWS certificates

- terraform/aws/environments/core/7-public-ingress/main.tf
- terraform/aws/environments/core/7-public-ingress/variables.tf
- terraform/aws/modules/public-ingress/nginx-public.tf
- terraform/aws/modules/public-ingress/nginx_values.yaml
- terraform/aws/modules/public-ingress/providers.tf
- terraform/aws/modules/public-ingress/variables.tf
Add a public ingress module
today it is used by the core env
> public-ingress: add nginx for public access

- terraform/aws/modules/bind-server/bind-servers.tf
- terraform/aws/modules/cluster-post-installation/blackbox.tf
- terraform/aws/modules/cluster-post-installation/es-curator.tf
- terraform/aws/modules/cluster-post-installation/fluent-bit.tf
- terraform/aws/modules/cluster-post-installation/flux.tf
- terraform/aws/modules/cluster-post-installation/grafana.tf
- terraform/aws/modules/cluster-post-installation/grafana_dashboard_configmaps.tf
- terraform/aws/modules/cluster-post-installation/ingress-internal.tf
- terraform/aws/modules/cluster-post-installation/kibana.tf
- terraform/aws/modules/cluster-post-installation/prometheus-client.tf
- terraform/aws/modules/cluster-post-installation/prometheus.tf
- terraform/aws/modules/elasticsearch/cloudwatch.tf
Changing paths to adapt to Gitlab deployments
> Changing paths to adapt to Gitlab deployments

- terraform/aws/modules/customer-web-server/web-server.tf
Changing path for customer web server
> Changing path for customer web server

- terraform/aws/modules/cluster-post-installation/provisioner-db.tf
- terraform/aws/modules/customer-web-server/web-server.tf
Fixes of variables to be updated for the addition of Pritunl VPN cidrs alongside with the current VPN
https://mattermost.atlassian.net/browse/MM-24216
> variables fixes for pritunl cidr

- terraform/aws/environments/test/4-command-and-control/3-cluster-post-installation/main.tf
- terraform/aws/environments/test/4-command-and-control/3-cluster-post-installation/variables.tf
- terraform/aws/environments/test/4-command-and-control/4-route53-registration/main.tf
- terraform/aws/environments/test/4-command-and-control/4-route53-registration/variables.tf
- terraform/aws/modules/customer-web-server/variables.tf
- terraform/aws/modules/customer-web-server/web-server.tf
- terraform/aws/modules/route53-registration/route53.tf
- terraform/aws/modules/route53-registration/variables.tf
change location of route53 for CWS
> change location of route53 for CWS

- terraform/aws/modules/gitlab/gitlab.tf
- terraform/aws/modules/gitlab/variables.tf
Adding variable for Gitlab chart values directory
> Adding variable for Gitlab chart values directory

- terraform/aws/modules/atlantis/atlantis.tf
- terraform/aws/modules/atlantis/nginx-internal.tf
- terraform/aws/modules/atlantis/variables.tf
Adding variable for Atlantis chart values directory
> Adding variable for Atlantis chart values directory

- terraform/aws/modules/public-ingress/nginx-public.tf
- terraform/aws/modules/public-ingress/variables.tf
Adding variable for nginx chart values directory
> Adding variable for nginx chart values directory

- terraform/aws/environments/dev/4-command-and-control/1-cluster/main.tf
- terraform/aws/environments/dev/4-command-and-control/1-cluster/output.tf
- terraform/aws/environments/dev/4-command-and-control/1-cluster/variables.tf
- terraform/aws/environments/dev/4-command-and-control/2-elasticsearch-cluster/main.tf
- terraform/aws/environments/dev/4-command-and-control/2-elasticsearch-cluster/variables.tf
- terraform/aws/environments/dev/4-command-and-control/3-cluster-post-installation/main.tf
- terraform/aws/environments/dev/4-command-and-control/3-cluster-post-installation/output.tf
- terraform/aws/environments/dev/4-command-and-control/3-cluster-post-installation/variables.tf
- terraform/aws/environments/dev/4-command-and-control/4-route53-registration/main.tf
- terraform/aws/environments/dev/4-command-and-control/4-route53-registration/variables.tf
adding development environment configuration for  Command and Control Cluster
https://mattermost.atlassian.net/browse/MM-23774
> add dev env configuration - command and control

- terraform/aws/modules/cluster-post-installation/flux.tf
Update fluxcloud to use a custom image with a mattermost exporter 
Already applied
> update fluxcloud to use custom image with mattermost

- terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf
Adding provisioner user permissions for resource group tagging
> Adding provisioner user permissions for resource group tagging

- terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf
Adding provisioner user permission to kms:TagResource
> Adding provisioner user permission to kms:TagResource

- terraform/aws/modules/customer-web-server/flux.tf
- terraform/aws/modules/customer-web-server/variables.tf
- terraform/aws/modules/customer-web-server/web-server.tf
Deployment of Flux for Customer Web Server - Portal
Latest images of CWS will be deployed via flux
https://mattermost.atlassian.net/browse/MM-24151
> Mm 24151 flux deploy portal

- terraform/aws/modules/customer-web-server/flux.tf
- terraform/aws/modules/customer-web-server/variables.tf
- terraform/aws/modules/customer-web-server/web-server.tf
- update environment variables for Customer Web Portal
- create new namespace for flux
https://mattermost.atlassian.net/browse/MM-24151
> Update environment variables for Customer Web Portal and new namespace creation

- terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf
This PR updates the KMS provisioner policy to solve permissions errors.
> Updating kms policy to solve KMS permissions issues

- terraform/aws/modules/pritunl/acm.tf
- terraform/aws/modules/pritunl/asg.tf
- terraform/aws/modules/pritunl/data.tf
- terraform/aws/modules/pritunl/iam.tf
- terraform/aws/modules/pritunl/locals.tf
- terraform/aws/modules/pritunl/nlb.tf
- terraform/aws/modules/pritunl/r53.tf
- terraform/aws/modules/pritunl/sg.tf
- terraform/aws/modules/pritunl/userdata.sh
- terraform/aws/modules/pritunl/variables.tf
Pritunl deployment
https://mattermost.atlassian.net/browse/MM-22904
> pritunl deployment

- terraform/aws/modules/vpc-setup/rds_enhanced_monitoring_iam.tf
- terraform/aws/modules/vpc-setup/variables.tf
Adding IAM resources for RDS enhanced monitoring
> MM-24279 Adding IAM resources for RDS enhanced monitoring

- terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf
Adapting RDS permissions to work with new multitenant Clusters
> Adapting RDS permissions to work with new multitenant Clusters

- terraform/aws/modules/cluster-post-installation/database-factory.tf
- terraform/aws/modules/cluster-post-installation/database-factory_user_permissions.tf
- terraform/aws/modules/cluster-post-installation/variables.tf
- terraform/aws/modules/route53-registration/route53.tf
This PR:
- Adds the Terraform code for the Mattermost cloud database factory deployment, service, ingress, etc.
- Adds the Terraform code for the Mattermost cloud database factory Route53 registration
- Adds the Terraform code for the Mattermost cloud database factory IAM user
https://mattermost.atlassian.net/browse/MM-24957
> [MM 24957] Mattermost cloud database factory Terraform deployment

- terraform/aws/modules/database-factory-scaling/database-factory-horizontal-scaling.tf
> Fixing the name of the bucket name and key variable

- terraform/aws/modules/database-factory-scaling/database-factory-horizontal-scaling.tf
- terraform/aws/modules/database-factory-scaling/variables.tf
Fixing small bug with variable naming
> Fixing variable for notifications hook

- terraform/aws/modules/cluster-post-installation/database-factory_user_permissions.tf
Add missing permission from Database Factory user.
> Adding CreateServiceLinkedRole permission for DB factory user

- terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf
Adds permissions to user for describing RDS endpoints
> MM-25556: added permissions to describe RDS endpoints

- terraform/aws/modules/teleport/providers.tf
- terraform/aws/modules/teleport/teleport.tf
- terraform/aws/modules/teleport/variables.tf
- Adding Terraform module to deploy Teleport application in k8s clusters
- https://mattermost.atlassian.net/browse/MM-24189
> [MM-24189] Adding Terraform module to deploy Teleport application in k8s clusters

- terraform/aws/modules/vpc-setup/outputs.tf
Add output for provisioning VPCs to reuse outside module
> MM-25774 Add output for provisioning VPCs to reuse outside module

- terraform/aws/modules/subnet-and-networking/security_groups.tf
- terraform/aws/modules/subnet-and-networking/variables.tf
- Add option to allow VPN access to the provisioning DB SGs
- This should be allowed only when env is DEV
https://mattermost.atlassian.net/browse/MM-26564
> [MM-26564] Add option to allow VPN access to the provisioning DB SGs.

- terraform/aws/modules/database-factory-scaling/cloud_db_factory_horizontal_scaling.tf
- terraform/aws/modules/database-factory-scaling/cloud_db_factory_vertical_scaling.tf
- terraform/aws/modules/database-factory-scaling/cloud_db_factory_vertical_scaling_user_permissions.tf
- terraform/aws/modules/database-factory-scaling/variables.tf
- Adding infrastructure for cloud db factory vertical scaling
- SQS Queue
- SNS Topic
- User Permissions
- K8s Cron Job
- Improvements in db factory horizontal scaling
https://mattermost.atlassian.net/browse/MM-24772
> [MM-24772] Adding infrastructure for cloud db factory vertical scaling

- terraform/aws/modules/pritunl/nlb.tf
- terraform/aws/modules/pritunl/sg.tf
Increase Pritunl CIDR range to accomodate more servers
> Increase Pritunl CIDR range

- terraform/aws/modules/teleport/teleport.tf
- terraform/aws/modules/teleport/variables.tf
Adding version support for Teleport helm deployment module
https://mattermost.atlassian.net/browse/MM-26962
> [MM-26962] Adding version support for Teleport helm deployment module

- terraform/aws/modules/gitlab/gitlab.tf
Upgrading Gitlab to 4.1.2
https://mattermost.atlassian.net/browse/MM-26956
> Upgrading Gitlab to 4.1.2

- terraform/aws/modules/cluster/worker_asg.tf
using oldestInstance because we dont replace the lauchconfiguration
> using oldestInstance because we dont replace the lauchconfiguration

- terraform/aws/modules/flux/flux.tf
- terraform/aws/modules/flux/output.tf
- terraform/aws/modules/flux/providers.tf
- terraform/aws/modules/flux/variables.tf
> module: add flux module

- terraform/aws/modules/flux/variables.tf
> flux: add missing variable

- terraform/aws/modules/flux/flux.tf
> flux: fixing terraform

- terraform/aws/modules/vpc-setup/cluster_nodes_iam.tf
Adding cloud provisioning node policy
https://mattermost.atlassian.net/browse/MM-27288
> [MM-27288] Adding cloud provisioning node policy

- terraform/aws/modules/flux/flux.tf
- terraform/aws/modules/flux/providers.tf
> flux: add missing helm repo

- terraform/aws/modules/provisioner/provisioner_user_permissions.tf
Adding dynamodb describe and delete table permissions
> Adding dynamodb describe and delete table permissions

- lambda-functions/create-rds-cloudwatch-alarm/main.go
rds/cloudwatch: filter out multitentant rds
> rds/cloudwatch: filter out multitentant rds

- terraform/aws/modules/database-factory/database_factory_user_permissions.tf
Adding DB factory permissions to handle creation and deletion of DB Parameter Groups
> Adding DB factory permissions to handle creation and deletion of DB Parameter Groups

- terraform/aws/modules/gitlab/chart_values.yaml
We are getting some errors when running some pipelines, and reading the docs and the issues, they recommend updating the default values for the Poll* settings
JIRA: https://mattermost.atlassian.net/browse/MM-28156
> add dome extra config for the gitlab runners

- terraform/aws/modules/provisioner-users/state_bucket.tf
- terraform/aws/modules/provisioner-users/variables.tf
- Moving kops state buckets to Terraform
- Adding policy to restrict down kops state access.
https://mattermost.atlassian.net/browse/MM-26766
> [MM-26760]6 Moving kops state buckets to Terraform, adding policy to restrict down state access.

- terraform/aws/modules/provisioner/locals.tf
- terraform/aws/modules/provisioner/provisioner.tf
- terraform/aws/modules/provisioner/variables.tf
Create IAM access ID and secret for provisioner via terraform and remove hardcoded values
https://mattermost.atlassian.net/browse/MM-28534
> Create IAM access ID and secret for provisioner via terraform

- terraform/aws/modules/atlantis/atlantis.tf
- terraform/aws/modules/atlantis/chart_values.yaml
- terraform/aws/modules/atlantis/variables.tf
Small improvements to Atlantis module
> Small improvements to Atlantis module

- terraform/aws/modules/vpc-setup/installation_s3_buckets.tf
Create installation filestore in each VPC
https://mattermost.atlassian.net/browse/MM-28463
> [MM-28463] Create installation filestore in each VPC.

- terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
Adding permissions for provisioner user to be able to use shared file store.
https://mattermost.atlassian.net/browse/MM-28989
> [MM-28989] Adding permissions for provisioner user to be able to use shared file store.

- terraform/aws/modules/database-factory-scaling/cloud_db_factory_vertical_scaling.tf
- terraform/aws/modules/database-factory-scaling/cloud_db_factory_vertical_scaling_user_permissions.tf
- terraform/aws/modules/vpc-setup/cluster_nodes_iam.tf
- Updating database factory components and policies
https://mattermost.atlassian.net/browse/MM-28888
https://mattermost.atlassian.net/browse/MM-28856
> [MM-28888] Updating database factory components and policies

- terraform/aws/modules/cluster-post-installation/metrics_bucket.tf
- terraform/aws/modules/cluster/worker_iam.tf
- Add long term Prometheus metrics buckets.
- Adapt worker node policy to allow access to metrics buckets.
https://mattermost.atlassian.net/browse/MM-28662
> [MM-28662] Add long term Prometheus metrics buckets.

- terraform/aws/modules/aws-certs/private_cert.tf
- terraform/aws/modules/aws-certs/variables.tf
- Adding support for Thanos in private SSL certs.
https://mattermost.atlassian.net/browse/MM-29080
> [MM-29080] Adding support for Thanos in private SSL certs.

- terraform/aws/modules/cluster-post-installation/prometheus_operator.tf
- terraform/aws/modules/cluster-post-installation/providers.tf
- Adding prometheus operator helm deployment in post installation module.
https://mattermost.atlassian.net/browse/MM-29079
> [MM-29079] Adding prometheus operator helm deployment in post installation module.

- terraform/aws/modules/cluster-post-installation/thanos-object-store-secret.tf
-  Adding kubernetes secret for thanos objstore configuration.
https://mattermost.atlassian.net/browse/MM-29113
> [MM-29113] Adding kubernetes secret for thanos objstore configuration.

- lambda-functions/grafana-aws-metrics/Gopkg.lock
- lambda-functions/grafana-aws-metrics/main.go
- terraform/aws/modules/grafana-aws-metrics/grafana-aws-metrics.tf
Updating metrics lambda to calculate IAMUser and IAMRole limits and utilisation.
> Updating metrics lambda to calculate IAMUser and IAMRole limits and utilisation.

- terraform/aws/modules/cluster-post-installation/metrics_server.tf
Deploy metrics server in CnC clusters
https://mattermost.atlassian.net/browse/MM-29546
> [MM-29546] Deploy metrics server in CnC clusters

- lambda-functions/prometheus-dns-registration-service/Gopkg.toml
- lambda-functions/prometheus-dns-registration-service/Makefile
- lambda-functions/prometheus-dns-registration-service/main.go
[MM-29697] Use pagination to get all route53 dns names
Jira: https://mattermost.atlassian.net/browse/MM-29697
> [MM-29697] Use pagination to get all route53 dns names

- terraform/aws/modules/elasticsearch/cloudwatch.tf
- terraform/aws/modules/elasticsearch/elasticsearch.tf
- terraform/aws/modules/elasticsearch/variables.tf
Create a new variable for retention in days in order to be changeable in different environments
https://mattermost.atlassian.net/browse/MM-29704
> Create retention in days variable for CW of ES

- lambda-functions/prometheus-dns-registration-service/main.go
- Add scrape timeout option in the prometheus configuration structure
> Add scrape timeout option in the prometheus configuration structure

- lambda-functions/prometheus-dns-registration-service/main.go
> Remove evaluation interval

- terraform/aws/modules/cluster/worker_iam.tf
- terraform/aws/modules/thanos-store-discovery/thanos_store_discovery.tf
- terraform/aws/modules/thanos-store-discovery/variables.tf
Adding Terraform module for Thanos store discovery tool deployment.
https://mattermost.atlassian.net/browse/MM-29900
> [MM-29900] Adding Terraform module for Thanos store discovery tool deployment.

- terraform/aws/modules/cluster-post-installation/grafana.tf
- terraform/aws/modules/cluster-post-installation/providers.tf
- terraform/aws/modules/cluster-post-installation/variables.tf
- migrate Grafana Helm chart from stable to official 
- Create a variable for Grafana chart version 
https://mattermost.atlassian.net/browse/MM-29738
> Migrate Grafana chart to official and update from 6.5.2 to 7.2.1

- lambda-functions/grafana-aws-metrics/main.go
Add pagination for IAM users and Roles
> Add pagination for IAM users and Roles

- terraform/aws/modules/cluster-post-installation/providers.tf
- terraform/aws/modules/cluster-post-installation/thanos.tf
- terraform/aws/modules/route53-registration/route53.tf
- Adding Thanos deployment Terraform templates.
https://mattermost.atlassian.net/browse/MM-29078
> [MM-29078] Adding Thanos deployment Terraform templates.

- terraform/aws/modules/subnet-and-networking-3az/security_groups.tf
- terraform/aws/modules/subnet-and-networking/security_groups.tf
Update MySQL Security Group tag
> Update MySQL Security Group tag

- lambda-functions/create-elb-cloudwatch-alarm/main.go
currently, the aws lambda only creates the cloudwatch alarms for LBs that follow a specific name, this PR removes that and creates the alarms for all LBS.
Also change the metric to check the Health Host metric
https://mattermost.atlassian.net/browse/MM-30003
> create LB alarms for all LBS

- terraform/aws/modules/cluster-post-installation/kibana.tf
- terraform/aws/modules/elasticsearch/kibana.tf
- terraform/aws/modules/route53-registration/route53.tf
Create a redirection for Kibana in order to use AWS' Elasticsearch Kibana's plugin with S3 bucket static site redirection and CloudFront 
https://mattermost.atlassian.net/browse/MM-30071
> Create a redirection to use AWS' Elasticsearch Kibana

- terraform/aws/modules/provisioner/provisioner.tf
Add missing helm3 volumes
https://mattermost.atlassian.net/browse/MM-29019
> [MM-29019] Include helm3 volumes

- lambda-functions/create-elb-cloudwatch-alarm/main.go
check which lb type we need to use to create the correct alarm
NONE
> check which lb type we need to use to create the correct alarm

- terraform/aws/modules/vpc-setup/installation_iam_users.tf
Add installation users, access and secret keys in secret manager, policies for s3 bucket access
https://mattermost.atlassian.net/browse/MM-30200
> [MM-30200] Add installation users, access and secret keys in secret manager, policies for s3 bucket access.

- lambda-functions/grafana-aws-metrics/main.go
- terraform/aws/modules/grafana-aws-metrics/grafana-aws-metrics.tf
> Add EC2 Instance quotas

- terraform/aws/modules/customer-web-server/web-server.tf
- terraform/aws/modules/database-factory-scaling/cloud_db_factory_horizontal_scaling.tf
- terraform/aws/modules/database-factory-scaling/cloud_db_factory_vertical_scaling.tf
- terraform/aws/modules/database-factory/database_factory.tf
- terraform/aws/modules/provisioner/provisioner.tf
- Set imagepolicy to IfNotPresent for Provisioner, Customer Web Server and Database Factory components.
> Set imagepolicy to IfNotPresent for Provisioner, Customer Web Server and Database Factory components.

- terraform/aws/modules/cluster/aws_auth_configmap.tf
- terraform/aws/modules/cluster/variables.tf
Add central monitoring user in cnc auth configmap cluster
> Add central monitoring user in cnc auth configmap cluster

- terraform/aws/modules/aws-certs/private_cert.tf
- terraform/aws/modules/aws-certs/public_cert.tf
- terraform/aws/modules/cluster-post-installation/blackbox.tf
- terraform/aws/modules/cluster-post-installation/es-curator.tf
- terraform/aws/modules/cluster-post-installation/fluent-bit.tf
- terraform/aws/modules/cluster-post-installation/metrics_bucket.tf
- terraform/aws/modules/cluster/kubeconfig.tf
- terraform/aws/modules/cluster/providers.tf
Make necessary changes for AWS provider 3.15 and terraform 0.13
https://mattermost.atlassian.net/browse/MM-28914
> Changes for aws provider 3.15 and terraform 0.13 

- terraform/aws/modules/cluster-post-installation/grafana_dashboard_configmaps.tf
Also changed order to be alphabetical for readability purposes
Adds Grafana dashboards for DNS monitoring. 
https://mattermost.atlassian.net/browse/MM-30522
> MM-30522: Add DNS grafana dashboards

- terraform/aws/modules/database-factory/database_factory_user_permissions.tf
- Add permission to modify db instance
> Add permission to modify db instance

- terraform/aws/modules/gitlab-monitoring/namespaces.tf
- terraform/aws/modules/gitlab-monitoring/prometheus.tf
- terraform/aws/modules/gitlab-monitoring/providers.tf
- terraform/aws/modules/gitlab-monitoring/route53.tf
- terraform/aws/modules/gitlab-monitoring/variables.tf
- Adding Gitlab cluster monitoring module.
https://mattermost.atlassian.net/browse/MM-30842
> [MM-30842] Adding Gitlab cluster monitoring module.

- terraform/aws/modules/atlantis/chart_values.yaml
Add multiple workflows to support multiple environments.
https://mattermost.atlassian.net/browse/MM-24482
> MM-24482: Add multiple workflows per environment

- terraform/aws/modules/atlantis/chart_values.yaml
<!--
Increase atlantis storage
`None`
> Increase atlantis dataStorage due to alarm

- terraform/aws/modules/cluster-post-installation/fluent-bit.tf
- terraform/aws/modules/cluster-post-installation/variables.tf
Needed to rollout a specific version which supports dnsConfig
Needed to rollout a specific version which supports dnsConfig
https://mattermost.atlassian.net/browse/MM-31157
> MM-31157: Enforce chart version for fluent-bit

- terraform/aws/modules/cluster-post-installation/grafana_dashboard_configmaps.tf
- Adding Nginx ingress controller Grafana dashboard configmap
- https://mattermost.atlassian.net/browse/MM-31325
> [MM-31325] Adding Nginx ingress controller Grafana dashboard configmap.

- terraform/aws/modules/security/shield.tf
- terraform/aws/modules/security/variables.tf
Configure AWS Shield. Add protected resources
Configure AWS Shield. Add protected resources. Add all resources needed to setup DRT.
https://mattermost.atlassian.net/browse/MM-30301
> Add aws_shield_protection to security module

- terraform/aws/modules/security/vpc_flow_logs.tf
Fix wrong naming
Fix wrong naming
`NONE`
> Fix S3 bucket naming

- terraform/aws/modules/atlantis/atlantis.tf
- terraform/aws/modules/atlantis/chart_values.yaml
Increase resources
Improve workflows.
Give more resources to atlantis
https://mattermost.atlassian.net/browse/MM-24482
> [MM_24482]: Atlantis: Improve workflows

- terraform/aws/modules/atlantis/providers.tf
> Cleanup to avoid plan error

- terraform/aws/modules/atlantis/atlantis.tf
> Fix namespace

- terraform/aws/modules/atlantis/chart_values.yaml
> Use correct terraform binary everywhere

- terraform/aws/modules/atlantis/providers.tf
Reverts mattermost/mattermost-cloud-monitoring#220
Want to check if this change is related with atlantis failures
> Revert "Remove config_path"

- terraform/aws/modules/customer-web-server/providers.tf
Remove deprecated helm data.
`NONE`
> Remove deprecated data

- terraform/aws/modules/atlantis/providers.tf
- terraform/aws/modules/chartmuseum/providers.tf
- terraform/aws/modules/flux/providers.tf
- terraform/aws/modules/gitlab/providers.tf
- terraform/aws/modules/public-ingress/providers.tf
- terraform/aws/modules/teleport/providers.tf
Add back load_config_file param
`NONE`
> Add back load_config_file param

- terraform/aws/modules/subnet-and-networking-3az/security_groups.tf
- terraform/aws/modules/subnet-and-networking/security_groups.tf
allowing VPN cidrs in test env for provisioning RDS SGs
https://mattermost.atlassian.net/browse/MM-30451
> add conditional to create vpn ingress for RDS both in test and dev

- terraform/aws/modules/bind-server/variables.tf
- Changing default instance type to newer architecture
- 
https://mattermost.atlassian.net/browse/MM-31707
> [MM-31707] Changing default instance type to newer architecture.

- terraform/aws/modules/cluster-post-installation/grafana_dashboard_configmaps.tf
create 2 new dashboards for grafana
- Bind DNS
- AWS RDS metrics for selected DBs
> Grafana new dashboards for Bind and RDS metrics

- terraform/aws/modules/bind-server/bind-servers.tf
- Allow access to Prometheus port in Bind SG
https://mattermost.atlassian.net/browse/MM-31333
> [MM-31333] Allow access to Prometheus port in Bind SG.

- terraform/aws/modules/bind-server/bind-servers.tf
- terraform/aws/modules/blackbox-target-discovery/blackbox_target_discovery.tf
- terraform/aws/modules/blackbox-target-discovery/variables.tf
- Add Bind servers env variable
https://mattermost.atlassian.net/browse/MM-31333
> [MM 31333] Add Bind servers env variable

- terraform/aws/modules/atlantis/chart_values.yaml
Atlantis configuration fixes
https://mattermost.atlassian.net/browse/MM-24482
> MM- 24482: Atlantis configuration fixes

- terraform/aws/modules/cluster-post-installation/grafana.tf
- terraform/aws/modules/cluster-post-installation/grafana_dashboard_configmaps.tf
add 2 new grafana dashboards
update dependencies of helm deployment of grafana
> Grafana new dashboards angelos

- terraform/aws/modules/flux/flux.tf
- terraform/aws/modules/gitlab-monitoring/prometheus.tf
Refactor directories structure for atlantis
https://mattermost.atlassian.net/browse/MM-24482
> Refactor directories structure for atlantis

- terraform/aws/modules/billing/budget.tf
- terraform/aws/modules/billing/variables.tf
Terraform module for budgets
https://mattermost.atlassian.net/browse/MM-31294
> MM-31294: Terraform module for budgets

- terraform/aws/modules/cluster-post-installation/cluster-autoscaler.tf
- terraform/aws/modules/cluster/worker_asg.tf
- terraform/aws/modules/cluster/worker_iam.tf
Add cluster autoscaler to EKS clusters
https://mattermost.atlassian.net/browse/MM-31881
> MM-31881: Add cluster autoscaler to EKS clusters

- terraform/aws/modules/database-factory-scaling/cloud_db_factory_horizontal_scaling.tf
- terraform/aws/modules/database-factory-scaling/cloud_db_factory_vertical_scaling.tf
- terraform/aws/modules/database-factory-scaling/variables.tf
- terraform/aws/modules/database-factory/database_factory.tf
- terraform/aws/modules/database-factory/variables.tf
- Migrating database factory in dedicated namespace.
- https://mattermost.atlassian.net/browse/MM-31728
> [MM-31728] Migrating database factory in dedicated namespace.

- terraform/aws/modules/provisioner/provisioner.tf
- terraform/aws/modules/provisioner/variables.tf
- Adding Gitlab OAUTH token for utilities
> Adding Gitlab OAUTH token for utilities

- terraform/aws/modules/cluster/master.tf
- terraform/aws/modules/cluster/variables.tf
- terraform/aws/modules/eks-cluster/master.tf
- terraform/aws/modules/eks-cluster/variables.tf
Enable EKS cluster master logging. 
https://mattermost.atlassian.net/browse/MM-31349
> Add logging to EKS master

- terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
Add actions needed on provisioner's iam policies
https://mattermost.atlassian.net/browse/MM-32561
> MM-32561: Add actions needed on provisioner's policies

- terraform/aws/modules/customer-web-server/variables.tf
- terraform/aws/modules/customer-web-server/web-server.tf
Missing CWS fields for the secret
> Added BLAPI settings for the CWS secret

- terraform/aws/modules/customer-web-server/web-server.tf
Update nginx ingress public class from nginx-controller to nginx
> change nginx ingress public class

- terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
- Adding autoscaling:DescribeLoadBalancers permissions for provisioner users.
https://mattermost.atlassian.net/browse/MM-32711
> [MM-32711] Adding autoscaling:DescribeLoadBalancers permissions for provisioner users.

- terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
Add autoscaling SuspendProcesses
https://mattermost.atlassian.net/browse/MM-32796
> MM-32796: Add SuspendProcesses

- terraform/aws/modules/fleet-controller/fleet_controller.tf
- terraform/aws/modules/fleet-controller/flux.tf
- terraform/aws/modules/fleet-controller/variables.tf
- Add support for fleet controller flux
https://mattermost.atlassian.net/browse/MM-32631
> [MM-32631] Add support for fleet controller flux.

- terraform/aws/modules/atlantis/atlantis.tf
- terraform/aws/modules/atlantis/variables.tf
Add atlantis instance on atlantis module
https://mattermost.atlassian.net/browse/MM-31971
> MM-31971: Add atlantis instance on atlantis module

- terraform/aws/modules/flux/flux.tf
- terraform/aws/modules/flux/variables.tf
We need to make it possible for all the scripts to define their own path to pass the chart values
https://mattermost.atlassian.net/browse/MM-32896
> [MM-32896] Make the path configurable

- terraform/aws/modules/fleet-controller/fleet_controller.tf
- terraform/aws/modules/fleet-controller/variables.tf
- Adding a variable for fleet controller max users filter
https://mattermost.atlassian.net/browse/MM-33048
> Adding a variable for fleet controller max users filter

- lambda-functions/deckhand/main.go
I was reviewing the initial PR on this lambda a bit late and i think we will need to compute `time.Now` outside of the main loop. Ignore me if this is by design.
N/A
> Compute time.now before jumping into the loop for filtering images

- terraform/aws/modules/subnet-and-networking-3az/route_tables.tf
- terraform/aws/modules/subnet-and-networking-3az/variables.tf
- terraform/aws/modules/subnet-and-networking/route_tables.tf
- terraform/aws/modules/subnet-and-networking/variables.tf
- terraform/aws/modules/transit-gateway/tgw_attachment.tf
- terraform/aws/modules/transit-gateway/variables.tf
- Adding sec and gitlab routes via tgw in route tables.
https://mattermost.atlassian.net/browse/MM-33313
> [MM-33313] Adding sec and gitlab routes via tgw in route tables.

- lambda-functions/rds-cluster-events/main.go
- Automate opsgenie alert closure when the failover is complete
- https://mattermost.atlassian.net/browse/MM-33314
> [MM-33314] Automate opsgenie alert closure when the failover is complete

- terraform/aws/modules/customer-web-server/web-server.tf
- terraform/aws/modules/nginx/nginx-internal.tf
- terraform/aws/modules/nginx/nginx.tf
- terraform/aws/modules/nginx/variables.tf
- terraform/aws/modules/provisioner/route53.tf
- terraform/aws/modules/route53-registration/route53.tf
Separate nginx charts to internal and public
https://mattermost.atlassian.net/browse/MM-32273
> Separate nginx charts to internal and public

- terraform/aws/modules/elasticsearch/security_group.tf
- terraform/aws/modules/elasticsearch/variables.tf
Update kibana/ES CIDRs with new VPN's CIDR
> Update kibana cidrs with new vpn cidr

- lambda-functions/deckhand/main.go
- terraform/aws/modules/cleanup-unused-images/iam.tf
Remove dry-run mode after testing to run actually first time on Monday
1/3
> Fix permissions after testing

- terraform/aws/modules/cluster-post-installation/blackbox.tf
- terraform/aws/modules/cluster-post-installation/variables.tf
- terraform/aws/modules/route53-registration/route53.tf
-  Blackbox improvements and ingress deployment
https://mattermost.atlassian.net/browse/MM-31722
> [MM-31722] Blackbox improvements and ingress deployment

- terraform/aws/modules/atlantis/atlantis.tf
- terraform/aws/modules/atlantis/variables.tf
Avoid clash with EKS workers ASG
> Rename atlantis ASG.

- terraform/aws/modules/gitlab/rbac.tf
Additional RBAC needed for gitlab pipelines
> Fix RBAC for gitlab pipelines

- terraform/aws/modules/mattermost-apps-cloud-deployer/mattermost_apps_cloud_deployer.tf
- terraform/aws/modules/mattermost-apps-cloud-deployer/mattermost_apps_cloud_deployer_user_permissions.tf
- terraform/aws/modules/mattermost-apps-cloud-deployer/variables.tf
- terraform/aws/modules/mattermost-apps-provisioning/iam.tf
- terraform/aws/modules/mattermost-apps-provisioning/output.tf
- terraform/aws/modules/mattermost-apps-provisioning/s3.tf
- terraform/aws/modules/mattermost-apps-provisioning/sg.tf
- terraform/aws/modules/mattermost-apps-provisioning/variables.tf
- Mattermost apps cloud deployer components
- Infrastructure components needed by Mattermost apps bundle functions (IAM, SG, etc.)
- https://mattermost.atlassian.net/browse/MM-33535
> [MM-33535] Mattermost apps deployment components

- terraform/aws/modules/genesis-support/iam.tf
- terraform/aws/modules/genesis-support/ram.tf
- terraform/aws/modules/genesis-support/variables.tf
- Resource share for Enterprise TGWs 
- IAM role genesis assumption to add principals
https://mattermost.atlassian.net/browse/MM-34278
> MM-34278 Creating Resource share for Enterprise TGWs and IAM role

- terraform/aws/modules/security/variables.tf
- terraform/aws/modules/security/vpc_flow_logs.tf
Send VPC flow logs to security AWS account
https://mattermost.atlassian.net/browse/MM-34406
> Update vpc flow logs location to security account S3 buckets

- terraform/aws/modules/customer-web-server/cws_compliance.tf
- terraform/aws/modules/customer-web-server/variables.tf
- terraform/aws/modules/customer-web-server/web-server.tf
- Add CWS compliance cronjob and secret updates
https://mattermost.atlassian.net/browse/MM-34068
> [MM-34068] Add cws compliance cronjob and secret updates.

- terraform/aws/modules/cluster-post-installation/flux.tf
- terraform/aws/modules/customer-web-server/flux.tf
- terraform/aws/modules/fleet-controller/flux.tf
Update the image for fluxcloud to official. 
Thanks @cpanato for your magic and your PR https://github.com/topfreegames/fluxcloud/pull/8/files
https://mattermost.atlassian.net/browse/MM-32830
> Update image docker hub repo for fluxcloud

- lambda-functions/deckhand/main.go
Use AMI Name instead of tag Name
https://mattermost.atlassian.net/browse/MM-34769
> Use AMI Name instead of tag Name

- terraform/aws/modules/atlantis/chart_values.yaml
This PR includes changes in:
- cpu reqeuests/limits
- use latest atlantis version docker image
- update repo config
https://mattermost.atlassian.net/browse/MM-34788
> Fix atlantis and change the repo config

- terraform/aws/modules/mattermost-apps-provisioning/iam.tf
- Removing unnecessary s3 permission
https://mattermost.atlassian.net/browse/MM-34988
> [MM-34988] Removing unnecessary s3 permission

- terraform/aws/modules/elasticsearch/monitoring.tf
Fix missing client ID for some alarms
https://mattermost.atlassian.net/browse/MM-34089
> Add client ID for alarms

- terraform/aws/modules/cleanup-unused-images/lambdas.tf
- terraform/aws/modules/cleanup-unused-images/locals.tf
- terraform/aws/modules/cleanup-unused-images/variables.tf
Remove unneeded variable
https://mattermost.atlassian.net/browse/MM-34468
> Remove unneeded variable

- terraform/aws/modules/customer-web-server/web-server.tf
- terraform/aws/modules/provisioner/provisioner-db.tf
Add tags to use on cost allocation
https://mattermost.atlassian.net/browse/MM-31550
> Add tags to use on cost allocation

- terraform/aws/modules/atlantis/chart_values.yaml
A typo breaks the repo yaml for atlantis
Simple fix
> Fix typo for atlantis repos yaml

- terraform/aws/modules/cluster-post-installation/grafana_dashboard_configmaps.tf
- Add Fluentbit Grafana dashboard
- https://mattermost.atlassian.net/browse/MM-35212
> [MM-35212] Add Fluentbit Grafana dashboard

- terraform/aws/modules/atlantis/rbac.tf
Atlantis needs also to get services
> Atlantis needs also to get services

- terraform/aws/modules/argocd/argocd.tf
- terraform/aws/modules/argocd/variables.tf
- Adding Argocd module for cnc cluster bootstrap
https://mattermost.atlassian.net/browse/MM-35460
> [MM-35460] Adding Argocd module for cnc cluster bootstrap

- terraform/aws/modules/cluster/worker_asg.tf
This resource should be handled by cluster autoscaler
This resource should be handled by cluster autoscaler
No ticket
> Ignore desired_capacity changes

- terraform/aws/modules/mattermost-apps-provisioning/iam.tf
- Restrict down policy for apps provisioning
https://mattermost.atlassian.net/browse/MM-35610
> [MM-35610] Restrict down policy for apps provisioning

- terraform/aws/modules/cluster/variables.tf
If this commit applied it will remove from cluster module an obsolete variable
https://mattermost.atlassian.net/browse/MM-35830
> Removes unused variable

- terraform/aws/modules/route53-registration/route53.tf
- terraform/aws/modules/route53-registration/variables.tf
- Add control for AWAT, portal private and private public route53 endpoints
> [MM-36620] Add control for AWAT, portal private and private public route53 endpoints

- terraform/aws/modules/subnet-and-networking-4az/internet_gtw.tf
- terraform/aws/modules/subnet-and-networking-4az/nat_gtw.tf
- terraform/aws/modules/subnet-and-networking-4az/provisioner_db_parameter_group.tf
- terraform/aws/modules/subnet-and-networking-4az/provisioner_db_subnet_group.tf
- terraform/aws/modules/subnet-and-networking-4az/route_tables.tf
- terraform/aws/modules/subnet-and-networking-4az/security_groups.tf
- terraform/aws/modules/subnet-and-networking-4az/subnet.tf
- terraform/aws/modules/subnet-and-networking-4az/transit_gtw.tf
- terraform/aws/modules/subnet-and-networking-4az/variables.tf
- terraform/aws/modules/vpc-setup/vpc.tf
- Add subnet module for 4az subnet creation
- https://mattermost.atlassian.net/browse/MM-32760
> [MM-32760] Add subnet module for 4az subnet creation

- terraform/aws/modules/cluster/providers.tf
- terraform/aws/modules/cluster/variables.tf
- terraform/aws/modules/cluster/worker_asg.tf
- terraform/aws/modules/cluster/worker_iam.tf
- terraform/aws/modules/eks-cluster/aws_auth_configmap.tf
- terraform/aws/modules/eks-cluster/providers.tf
- terraform/aws/modules/eks-cluster/variables.tf
- terraform/aws/modules/eks-cluster/worker_asg.tf
- terraform/aws/modules/eks-cluster/worker_iam.tf
- terraform/aws/modules/eks-managed-node-groups/node_groups.tf
- terraform/aws/modules/eks-managed-node-groups/variables.tf
- Replace ASGs for EKS with managed nodes
https://mattermost.atlassian.net/browse/MM-36075
> [MM-36075] Replace ASGs for EKS with managed nodes

- terraform/aws/modules/gitlab/providers.tf
- terraform/aws/modules/teleport/providers.tf
Remove load_config entry as it is no longer supported
> Remove load_config entry as it is no longer supported

- terraform/aws/modules/cluster/aws_auth_configmap.tf
- terraform/aws/modules/cluster/variables.tf
- terraform/aws/modules/eks-cluster/aws_auth_configmap.tf
- terraform/aws/modules/eks-cluster/variables.tf
Add permissions to be able to get EKS information via the cοnsole
https://mattermost.atlassian.net/browse/MM-36896
> [MM-36896] Add permissions to be able to get EKS information via the cοnsole

- terraform/aws/modules/provisioner-users/stackrox_bundle_bucket.tf
- terraform/aws/modules/provisioner-users/variables.tf
Enhance security to allow only admin roles to access buckets
> [MM-37102] Enhance security to allow only admin roles to access buckets

- .circleci/config.yml
- terraform/aws/modules/argocd/argocd.tf
- terraform/aws/modules/argocd/variables.tf
- Adapt Argocd module to be able to deploy it in core account
https://mattermost.atlassian.net/browse/MM-37200
> MM-37200 Adapt Argocd module to be able to deploy it in core account

- terraform/aws/modules/route53-registration/route53.tf
- terraform/aws/modules/route53-registration/variables.tf
Add Chimera DNS record to Route 53.
https://mattermost.atlassian.net/browse/MM-37310
> Add Chimera DNS record

- terraform/aws/modules/route53-registration/route53.tf
Switch Chimera route to public LB.
> Fix Chimera route registration

- terraform/aws/modules/awat/awat_db.tf
- terraform/aws/modules/awat/locals.tf
- terraform/aws/modules/awat/variables.tf
Issue: MM-38045
Seems that there is buggy behaviour on terraform and when a module has variables names that co-exist in another module.
https://mattermost.atlassian.net/browse/MM-38045
> Change AWAT variables naming

- terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
Needed permission to delete a dev cluster.
Issue: MM-38265
Add missing IAM permission, which was needed to delete a cluster. 
https://mattermost.atlassian.net/browse/MM-38265
> Add missing IAM permission.

- terraform/aws/modules/cluster/worker_iam.tf
Add  assume role permission for node worker role required for Kube2IAM
https://mattermost.atlassian.net/browse/MM-38319
> MM-38229-assumerole-permission-kube2iam

- terraform/aws/modules/route53-registration/route53.tf
- terraform/aws/modules/route53-registration/variables.tf
Issue: MM-38444
Add kubecost internal nginx endpoints
https://mattermost.atlassian.net/browse/MM-38444
> Add kubecost internal nginx endpoints

- terraform/aws/modules/route53-registration/providers.tf
- terraform/aws/modules/route53-registration/route53.tf
- terraform/aws/modules/route53-registration/variables.tf
Ability to pass custom CNAME instead of public nginx hostname for Customer Web Server
Ticket: https://mattermost.atlassian.net/browse/MM-38605
> Add ability to use custom CNAME for Customer Web Server public

- terraform/aws/modules/route53-registration/route53.tf
- terraform/aws/modules/route53-registration/variables.tf
-  Add public record for cloud Mattermost Push Proxy deployment
https://mattermost.atlassian.net/browse/MM-39813
> [MM-39813] Add public record for cloud Mattermost Push Proxy deployment

- terraform/aws/modules/gitlab-runner/README.md
- terraform/aws/modules/gitlab-runner/iam.tf
- terraform/aws/modules/gitlab-runner/locals.tf
- terraform/aws/modules/gitlab-runner/main.tf
- terraform/aws/modules/gitlab-runner/variables.tf
Module for creation of a bucket about gitlab runners and the required IAM role.
Ticket: https://mattermost.atlassian.net/browse/MM-38616
> Add module for gitlab runner for terraform

- terraform/aws/modules/cluster/eks_addon.tf
- terraform/aws/modules/cluster/master_iam.tf
- terraform/aws/modules/cluster/variables.tf
- terraform/aws/modules/eks-cluster/eks_addon.tf
- terraform/aws/modules/eks-cluster/master_iam.tf
- terraform/aws/modules/eks-cluster/variables.tf
- Add support for EKS addons
https://mattermost.atlassian.net/browse/MM-36925
> [MM-36925] Add support for EKS addons

- terraform/aws/modules/database-factory/database_factory_user_permissions.tf
Issue: MM-40227
Add permissions so DB factory role be able to manipulate Parameter Groups
https://mattermost.atlassian.net/browse/MM-40227
> Add permissions to DB factory role

- terraform/aws/modules/pritunl/acm.tf
- Fix broken Pritunl module
https://mattermost.atlassian.net/browse/MM-40321
> [MM-40321] Fix broken Pritunl module

- terraform/aws/modules/database-factory/database_factory_user_permissions.tf
- terraform/aws/modules/database-factory/variables.tf
Temporary rollback db factory to user based authentication until we test all our services with kube2iam in test environment.
https://mattermost.atlassian.net/browse/MM-40519
> MM-40519 Temporary rollback db factory to user based authentication

- terraform/aws/modules/cluster/worker_iam.tf
- terraform/aws/modules/loki/s3.tf
- terraform/aws/modules/loki/variables.tf
- Add Loki storage and Iam permissions
https://mattermost.atlassian.net/browse/MM-40224
> [MM-40224] Add Loki storage and Iam permissions

- terraform/aws/modules/cluster/variables.tf
- terraform/aws/modules/cluster/worker_asg.tf
- terraform/aws/modules/eks-managed-node-groups/spot_node_groups.tf
- terraform/aws/modules/eks-managed-node-groups/variables.tf
Issue: MM-40782
Add managed EKS group with spot instances
https://mattermost.atlassian.net/browse/MM-40782
> Add managed EKS group with spot instances

- terraform/aws/modules/eks-cluster/variables.tf
- terraform/aws/modules/eks-cluster/worker_asg.tf
- Add spot worker group in core CnC
> Add spot worker group in core CnC

- terraform/aws/modules/cluster/worker_iam.tf
- Remove DynamoDB permissions and attach policy to role
> Remove DynamoDB permissions and attach policy to role

- terraform/aws/modules/route53-registration/route53.tf
- terraform/aws/modules/route53-registration/variables.tf
- Add support for loki-gateway R53 record
> Add support for loki-gateway R53 record

- terraform/aws/modules/route53-registration/route53.tf
- terraform/aws/modules/route53-registration/variables.tf
> Fix resource name

- terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
- terraform/aws/modules/provisioner-users/variables.tf
We need extra permissions for the AWAT S3 bucket for data import.
Ticket: https://mattermost.atlassian.net/browse/MM-41181
> [provisioner] Add extra permissions to policy of provisioner user

- terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
- terraform/aws/modules/provisioner-users/variables.tf
Add permissions for cross-account awat access
> Add permissions for cross-account awat access

- terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
- Fix AWAT policy deployment check
> Fix AWAT policy deployment check

- terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
- Rearrange policy attachments to solve the 10 policy limit
> Rearrange policy attachments to solve the 10 policy limit

- aws/migrate-to-cloud/README.md
- aws/migrate-to-cloud/iam.tf
- aws/migrate-to-cloud/variables.tf
Issue:
Module to migrate self hosted workspace to cloud
```release-note
NONE
```
> Module to migrate self hosted workspace to cloud

- aws/community-infra/README.md
- aws/community-infra/locals.tf
- aws/community-infra/provisioning_iam.tf
- aws/community-infra/provisioning_s3.tf
- aws/community-infra/variables.tf
Module to setup AWS resources for community & Bifrost. e.g IAM, S3 , cross-region replication etc.
(https://mattermost.atlassian.net/browse/MM-42367)
```release-note
NONE
```
> Mm 42367 bifrost resources

- aws/community-infra/example/main.tf
- aws/community-infra/provisioning_s3.tf
https://mattermost.atlassian.net/browse/MM-42367
Added an example for community usage with small typo fix.
```release-note
NONE
```
> MM-42367 added an example & fix the variable case

- README.md
- aws/community-infra/provisioning_iam.tf
- aws/transit-gateway-setup/tgw.tf
Added detail about tagging standardization for TF modules & small variable typo fix
```release-note
NONE
```
> Mm 42677 tagging standardisation for TF modules 

- aws/eks-managed-node-groups/node_groups.tf
- aws/eks-managed-node-groups/spot_node_groups.tf
- aws/eks-managed-node-groups/variables.tf
Issue: MM-43455
Control the kubernetes version for managed nodes
https://mattermost.atlassian.net/browse/MM-43455
```release-note
NONE
```
> Control the kubernetes version for managed nodes

- aws/blapi/README.md
- aws/blapi/locals.tf
- aws/blapi/output.tf
- aws/blapi/rds.tf
- aws/blapi/variables.tf
Issue: MM-43515
Add module for blapi database
https://mattermost.atlassian.net/browse/MM-43515
```release-note
NONE
```
> Add module for blapi database

- aws/blapi/rds.tf
Issue: MM-43515
Fix some blapi resources
https://mattermost.atlassian.net/browse/MM-43515
```release-note
NONE
```
> Fix some blapi resources

- aws/cluster/variables.tf
- aws/cluster/worker_asg.tf
- aws/eks-managed-node-groups/README.md
- aws/eks-managed-node-groups/node_groups.tf
- aws/eks-managed-node-groups/spot_node_groups.tf
- aws/eks-managed-node-groups/variables.tf
Is not applicable when using custom AMIs
Issue:
Remove kubernetes_version
```release-note
ΝΟΝΕ
```
> Remove kubernetes_version

- aws/cluster/README.md
- aws/cluster/variables.tf
- aws/cluster/worker_asg.tf
- aws/eks-managed-node-groups/README.md
- aws/eks-managed-node-groups/node_groups.tf
- aws/eks-managed-node-groups/spot_node_groups.tf
- aws/eks-managed-node-groups/variables.tf
Issue:
Add ebs_optimized variable
```release-note
NONE
```
> Add ebs_optimized variable

- aws/vpc-setup/cluster_nodes_iam.tf
- aws/vpc-setup/variables.tf
- Add flag to avoid duplicate node policy deployments for 4az vpcs
```release-note
- Add flag to avoid duplicate node policy deployments for 4az vpcs
```
> [MM-44077] Add flag to avoid duplicate node policy deployments for 4az vpcs

- aws/vpc-setup/rds_enhanced_monitoring_iam.tf
- aws/vpc-setup/variables.tf
- Add flag to avoid duplicate iam role deployments for 4az vpcs
```release-note
- Add flag to avoid duplicate iam role deployments for 4az vpcs
```
> [MM-44077] Add flag to avoid duplicate iam role deployments for 4az vpcs

- aws/vpc-setup/installation_s3_buckets.tf
Added a lifecycle block with ignore-replication to handle the drift for replication configuration of the community's provisioning bucket.
https://mattermost.atlassian.net/browse/MM-44480
```release-note
```
> MM-44480 Added ignore block for S3 replication configuration

- aws/blapi/README.md
- aws/blapi/iam.tf
- aws/blapi/s3.tf
- aws/blapi/variables.tf
Issue: MM-44304
Add s3 bucket for pipelinewise
https://mattermost.atlassian.net/browse/MM-44304
```release-note
NONE
```
> Add s3 bucket for pipelinewise

- aws/account-alerts/account_alerts.tf
- aws/bind-server/bind-server-network-attachment.tf
- aws/cleanup-unused-images/lambdas.tf
- aws/ebs-janitor/ebs_janitor.tf
- aws/elb-cleanup/elb-cleanup-lambda.tf
- aws/grafana-aws-metrics/grafana-aws-metrics.tf
- aws/lambda-promtail/README.md
- aws/lambda-promtail/cloudwatch.tf
- aws/lambda-promtail/iam.tf
- aws/lambda-promtail/lambdas.tf
- aws/lambda-promtail/locals.tf
- aws/lambda-promtail/variables.tf
- aws/logs-to-opensearch/lambdas.tf
- aws/rds-cluster-events/rds-cluster.events.tf
- aws/server-auth/cloud-server-auth.tf
Issue: CLD-2297
Lambda Promtail module
https://mattermost.atlassian.net/browse/CLD-2297
```release-note
NONE
```
> Lambda Promtail module

- aws/lambda-promtail/lambdas.tf
- aws/lambda-promtail/variables.tf
Issue: CLD-2297
Minor changes to lambda-promtail
https://mattermost.atlassian.net/browse/CLD-2297
```release-note
NONE
```
> Minor changes to lambda-promtail

- aws/lambda-promtail/lambdas.tf
Issue: CLD-2439
Fix aws_lamda_function for promtail
https://mattermost.atlassian.net/browse/CLD-2439
```release-note
NONE
```
> Fix aws_lamda_function for promtail

- aws/lambda-promtail/iam.tf
Fix iam role for lambda promtail
```release-note
NONE
```
> Fix iam role for lambda promtail

- aws/cluster/README.md
- aws/cluster/worker_sg.tf
- aws/eks-cluster/README.md
- aws/eks-cluster/kubeconfig.tf
- aws/eks-cluster/worker_sg.tf
- aws/pritunl/README.md
- aws/pritunl/asg.tf
Remove all template_file references as it's a deprecated provider. Replace with templatefile function.
https://mattermost.atlassian.net/browse/CLD-2311
```release-note
Remove all template_file references
```
> Remove all template_file references

- aws/lambda-promtail/cloudwatch.tf
- aws/lambda-promtail/iam.tf
- aws/lambda-promtail/lambdas.tf
- aws/lambda-promtail/variables.tf
Issue:
Remove bucket events functionality as we don't need it for now
```release-note
NONE
```
> Remove bucket events functionality as we don't need it for now

- aws/rds-global-cluster/README.md
- aws/rds-global-cluster/example/main.tf
- aws/rds-global-cluster/global-db-cluster.tf
- aws/rds-global-cluster/locals.tf
- aws/rds-global-cluster/variables.tf
A terraform module to manage the Aurora Global RDS cluster.It would be helpful to create a global cluster in prod when we decide to migrate the community server to the prod account.
https://mattermost.atlassian.net/browse/CLD-682
```release-note
N/A
```
> CLD-682 Global RDS cluster module

- aws/elb-cleanup/elb-cleanup-lambda.tf
Issue: CLD-2479
Consolidate lambdas to use same naming convention for handler
https://mattermost.atlassian.net/browse/CLD-2479
```release-note
NONE
```
> Consolidate lambdas to use same naming convention for handler

- aws/ebs-janitor/README.md
- aws/ebs-janitor/ebs_janitor.tf
- aws/ebs-janitor/variables.tf
- aws/elb-cleanup/README.md
- aws/elb-cleanup/variables.tf
Issue: CLD-2500
Add dryRun ability to ebs-janitor
https://mattermost.atlassian.net/browse/CLD-2500
```release-note
NONE
```
> Add dryRun ability to ebs-janitor

- .vscode/settings.json
- aws/blapi/rds.tf
- aws/gitlab/gitlab-db.tf
- aws/pritunl/nlb.tf
- aws/provisioner/provisioner-db.tf
Fix some Terraform 1.x errors for upgrade
Addresses: https://mattermost.atlassian.net/browse/CLD-2311
```release-note
- Fix some Terraform 1.x errors for upgrade
```
> Fix some Terraform 1.x errors for upgrade

- aws/route53-registration/route53.tf
- aws/route53-registration/variables.tf
Added a TF CF Record name resource for Chimera. (We already have resources for Portal & CWS but need to import them to TF state for each environment)
https://mattermost.atlassian.net/browse/CLD-2485
```release-note
N/A
```
> Added CF CNAME resources for Chimera

- aws/lambda-promtail/README.md
- aws/lambda-promtail/cloudwatch.tf
- aws/lambda-promtail/variables.tf
Issue: CLD-3747
[loki-promtail] Add variable for filter_pattern
https://mattermost.atlassian.net/browse/CLD-3747
```release-note
NONE
```
> [loki-promtail] Add variable for filter_pattern

- aws/atlantis/rbac.tf
Add deployments to Atlantis RBAC permissions
Discovered as part of https://mattermost.atlassian.net/browse/CLD-3734
```release-note
- Add deployments to Atlantis RBAC permissions
```
> Add deployments to Atlantis RBAC permissions

- aws/lambda-promtail/README.md
- aws/lambda-promtail/lambdas.tf
- aws/lambda-promtail/variables.tf
Issue: CLD-3758
Add new environment variable to lambda-promtail
https://mattermost.atlassian.net/browse/CLD-3758
```release-note
NONE
```
> Add new environment variable to lambda-promtail

- aws/community-on-demand/README.md
- aws/community-on-demand/example/main.tf
- aws/community-on-demand/example/variables.tf
- aws/community-on-demand/locals.tf
- aws/community-on-demand/providers.tf
- aws/community-on-demand/provisioning_iam.tf
- aws/community-on-demand/provisioning_s3.tf
- aws/community-on-demand/variables.tf
- aws/database-factory-scaling/cloud_db_factory_vertical_scaling.tf
TF module to create cloud resources like S3 , IAM etc for community on demand
https://mattermost.atlassian.net/browse/CLD-3720
```release-note
N/A
```
> CLD 3720 Resources for community on demand

- aws/subnet-and-networking-4az/security_groups.tf
- aws/subnet-and-networking/security_groups.tf
Adding proper ingress all to calls security group
Fixes https://mattermost.atlassian.net/browse/CLD-2613
```release-note
- Adding proper ingress all to calls security group
```
> Adding proper ingress all to calls security group

- aws/database-factory/database_factory_user_permissions.tf
Proper json formatting for IAM policy db-factory
Fixes CLD-3865
```release-note
- Proper json formatting for IAM policy db-factory
```
> Proper json formatting for IAM policy db-factory

- aws/elrond/README.md
- aws/elrond/elrond-db.tf
- aws/elrond/locals.tf
- aws/elrond/output.tf
- aws/elrond/providers.tf
- aws/elrond/variables.tf
- Add Terraform module for Elrond DB resources
```release-note
- Add Terraform module for Elrond DB resources
```
> [CLD-3908] Add Terraform module for Elrond DB resources

- aws/community-on-demand/provisioning_iam.tf
- aws/community-on-demand/provisioning_s3.tf
Fixed Provider related resource issues for community on demand.
https://mattermost.atlassian.net/browse/CLD-1422
```release-note
N/A
```
> Cld 1422 fix provider related resource issues

- aws/route53-registration/route53.tf
- aws/route53-registration/variables.tf
- Add alertmanager R53 record support
```release-note
- Add alertmanager R53 record support
```
> [CLD-4110] Add alertmanager R53 record support

- aws/blapi/variables.tf
> [CLD-3946] Module fixes

- aws/subnet-and-networking-3az/variables.tf
- aws/subnet-and-networking-4az/variables.tf
> CLD-3946 Fix teleport cidr

- aws/eks-cluster/eks_addon.tf
- aws/eks-cluster/variables.tf
- Add ebs csi addon for eks cluster module
```release-note
- Add ebs csi addon for eks cluster module
```
> [CLD-3946] Add ebs csi addon for eks cluster module

- aws/eks-cluster/aws_auth_configmap.tf
- aws/eks-cluster/variables.tf
- Fix module
```release-note
- Fix module
```
> [CLD-3946] Fix module

- aws/cluster/worker_iam.tf
- aws/eks-cluster/worker_iam.tf
-  Fix permissions for EBS CSI EKS addon
```release-note
-  Fix permissions for EBS CSI EKS addon
```
> [CLD-4238] Fix permissions for EBS CSI EKS addon

- aws/elasticsearch/elasticsearch.tf
- aws/elasticsearch/variables.tf
Add TLS security policy to elasticsearch module
https://mattermost.atlassian.net/browse/CLD-4223
```release-note
- Add TLS security policy to elasticsearch module
```
> Add TLS security policy to elasticsearch module

- aws/aws-certs/README.md
- aws/aws-certs/public_cert.tf
- aws/aws-certs/variables.tf
Issue: CLD-4328
Remove unneeded certification validation resources
https://mattermost.atlassian.net/browse/CLD-4328
```release-note
NONE
```
> Remove unneeded certification validation resources

- aws/elasticsearch/elasticsearch.tf
- aws/elasticsearch/variables.tf
Add new elasticsearch master user/pass combo
https://mattermost.atlassian.net/browse/CLD-4333
```release-note
- Add new elasticsearch master user/pass combo
```
> Add new elasticsearch master user/pass combo

- aws/elasticsearch/elasticsearch.tf
- aws/elasticsearch/variables.tf
Fix master user for elasticsearch
https://mattermost.atlassian.net/browse/CLD-4334
```release-note
- Fix master user for elasticsearch
```
> Fix master user for elasticsearch

- aws/provisioner-users/provisioner_user_permissions.tf
- aws/vpc-setup/cluster_nodes_iam.tf
Issue: CLD-4344
Add missing permissions for kops
https://mattermost.atlassian.net/browse/CLD-4344
```release-note
NONE
```
> Add missing permissions for kops

- aws/awat/awat_db.tf
- aws/awat/variables.tf
- aws/blapi/rds.tf
- aws/blapi/variables.tf
- aws/customer-web-server/variables.tf
- aws/customer-web-server/web-server.tf
- aws/provisioner/provisioner-db.tf
- aws/provisioner/variables.tf
Issue: CLD-4376
Add performance_insights support
https://mattermost.atlassian.net/browse/CLD-4376
```release-note
NONE
```
> Add performance_insights support

- aws/route53-registration/route53.tf
- Remove old non used Grafana record
```release-note
- Remove old non used Grafana record
```
> [CLD-4429] Remove old non used Grafana record

- aws/aurora-cluster/providers.tf
- aws/aurora-cluster/rds.tf
- aws/aurora-cluster/variables.tf
- aws/awat/awat_db.tf
- aws/awat/variables.tf
- aws/blapi/rds.tf
- aws/blapi/variables.tf
- aws/elrond/elrond-db.tf
- aws/elrond/variables.tf
Add AWAT aurora cluster
Add aurora-cluster module and use it for blapi, awat and elrond services.
https://mattermost.atlassian.net/browse/CLD-4009
```release-note
NONE
```
> Add aurora-cluster module

- aws/customer-web-server/web-server.tf
- aws/provisioner/provisioner-db.tf
Issue: CLD-4530
Fix deprecation conflict
https://mattermost.atlassian.net/browse/CLD-4530
```release-note
NONE
```
> Fix deprecation conflict

- aws/awat/variables.tf
- aws/blapi/variables.tf
- aws/elrond/variables.tf
Remove performance_insights default values
https://mattermost.atlassian.net/browse/CLD-4009
```release-note
NONE
```
> Remove performance_insights default values

- aws/awat/awat_db.tf
fix deprecation conflict / awat
```release-note
NONE
```
> fix deprecation conflict / awat

- aws/aurora-cluster/rds.tf
- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/awat/locals.tf
- aws/awat/variables.tf
- aws/elrond/README.md
- aws/elrond/elrond-db.tf
- aws/elrond/locals.tf
- aws/elrond/variables.tf
Blapi, Elrond
Cleanup legacy databases for internal services
https://mattermost.atlassian.net/browse/CLD-4009
```release-note
NONE
```
> Cleanup legacy databases for internal services

- aws/elrond/output.tf
Remove legacy output
```release-note
NONE
```
> Remove legacy output

- aws/provisioner/provisioner-db.tf
- aws/provisioner/variables.tf
Added SG rule for provisioner database access for GitLab
https://mattermost.atlassian.net/browse/CLD-4548
```release-note
None
```
> Added SG rule for provisioner db access for gitlab

- aws/static-site-s3/iam.tf
- aws/static-site-s3/providers.tf
- aws/static-site-s3/s3.tf
- aws/static-site-s3/variables.tf
Issue:
Module to create S3 static site
https://mattermost.atlassian.net/browse/CLD-4543
```release-note
NONE
```
> Module S3 static site

- aws/aurora-cluster/README.md
- aws/aurora-cluster/providers.tf
- aws/awat/README.md
- aws/awat/providers.tf
- aws/elrond/README.md
- aws/elrond/providers.tf
- aws/provisioner/README.md
- aws/provisioner/providers.tf
- aws/provisioner/provisioner-db.tf
- aws/provisioner/variables.tf
Minor fixes to docs and minimum required provider versions in several modules
Add aurora cluster to provisioner
https://mattermost.atlassian.net/browse/CLD-4009
```release-note
NONE
```
> Add aurora cluster to provisioner

- aws/customer-web-server/README.md
- aws/customer-web-server/locals.tf
- aws/customer-web-server/providers.tf
- aws/customer-web-server/variables.tf
- aws/customer-web-server/web-server.tf
> Add aurora cluster to CWS

- aws/aurora-cluster/rds.tf
- aws/aurora-cluster/variables.tf
Issue: CLD-4557
Support slowlogs exposure to aurora cluster module.
https://mattermost.atlassian.net/browse/CLD-4557
```release-note
NONE
```
> Support slowlogs exposure to aurora cluster module.

- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/blapi/README.md
- aws/blapi/rds.tf
- aws/customer-web-server/README.md
- aws/customer-web-server/web-server.tf
- aws/elrond/README.md
- aws/elrond/elrond-db.tf
- aws/provisioner/README.md
- aws/provisioner/provisioner-db.tf
Issue: CLD-4557
Update aurora-cluster module version used.
https://mattermost.atlassian.net/browse/CLD-4557
```release-note
NONE
```
> Update aurora-cluster module version used.

- aws/aurora-cluster/variables.tf
- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/blapi/README.md
- aws/blapi/rds.tf
- aws/customer-web-server/README.md
- aws/customer-web-server/web-server.tf
- aws/elrond/README.md
- aws/elrond/elrond-db.tf
- aws/provisioner/README.md
- aws/provisioner/provisioner-db.tf
Issue: CLD-4557
Fix typo in aurora-cluster
```release-note
NONE
```
> Fix typo in aurora-cluster

- aws/subnet-and-networking-3az/provisioner_db_parameter_group.tf
- aws/subnet-and-networking-4az/provisioner_db_parameter_group.tf
- aws/subnet-and-networking/provisioner_db_parameter_group.tf
- Add missing parameters in MySQL parameter group
```release-note
- Add missing parameters in MySQL parameter group
```
> [CLD-4646] Add missing parameters in MySQL parameter group

- aws/subnet-and-networking-3az/security_groups.tf
- aws/subnet-and-networking-3az/variables.tf
- aws/subnet-and-networking-4az/security_groups.tf
- aws/subnet-and-networking-4az/variables.tf
- aws/subnet-and-networking/security_groups.tf
- aws/subnet-and-networking/variables.tf
- Add tailscale vpn to db sec groups
```release-note
- Add tailscale vpn to db sec groups
```
> [CLD-4637] Add tailscale vpn to db sec groups

- aws/lambda-promtail/cloudwatch.tf
Issue: CLD-4658
Fix log_subscription_filter to avoid overwrite existing
https://mattermost.atlassian.net/browse/CLD-4658
```release-note
NONE
```
> Fix log_subscription_filter to avoid overwrite existing

- aws/blapi/output.tf
- aws/provisioner/output.tf
Cleanup legacy outputs
```release-note
NONE
```
> Cleanup legacy outputs

- aws/cluster/worker_asg.tf
- aws/eks-cluster/worker_asg.tf
- aws/eks-managed-node-groups/node_groups.tf
- aws/eks-managed-node-groups/spot_node_groups.tf
Issue: CLD-4762
Add KubernetesCluster label
https://mattermost.atlassian.net/browse/CLD-4762
```release-note
NONE
```
> Add KubernetesCluster label

- aws/vpc-setup/installation_iam_users.tf
- Add GetBucketLocation permission in Bifrost
```release-note
- Add GetBucketLocation permission in Bifrost
```
> [CLD-4863] Add GetBucketLocation permission in Bifrost

- aws/bastion-host-stitch/README.md
- aws/bastion-host-stitch/ec2.tf
- aws/bastion-host-stitch/providers.tf
- aws/bastion-host-stitch/variables.tf
- aws/blapi/README.md
- aws/blapi/rds.tf
- aws/blapi/variables.tf
Issue: CLD-4386
Bastion host for stitch module
https://mattermost.atlassian.net/browse/CLD-4387
```release-note
NONE
```
> Bastion host for stitch module

- aws/cluster/variables.tf
- aws/cluster/worker_asg.tf
- aws/eks-managed-node-groups/spot_node_groups.tf
- aws/eks-managed-node-groups/variables.tf
Issue: CLD-4802
Make EKS spot instance Groups AZ aware
https://mattermost.atlassian.net/browse/CLD-4802
```release-note
NONE
```
> Make EKS spot instance Groups AZ aware

- aws/cluster/README.md
- aws/cluster/aws_auth_configmap.tf
Summary
Fix auth-map configmap data conditional
Ticket Link
Fixes https://mattermost.atlassian.net/browse/CLD-4578
```release-note
NONE
```
> [CLD-4578]: fix auth-map configmap data conditional

- aws/cluster/aws_auth_configmap.tf
Create read-only k8s roles only for prod env
Fixes https://mattermost.atlassian.net/browse/CLD-4578
```release-note
NONE
```
> [CLD-4578]: Create read only role only for prod env

- aws/cluster/aws_auth_configmap.tf
Fix K8s cluster role for read-only user
https://mattermost.atlassian.net/browse/CLD-4578
```release-note
None
```
> [CLD-4578]: Fix k8s cluster role for read-only user

- aws/eks-cluster/argocd_iam.tf
- aws/eks-cluster/aws_auth_configmap.tf
- aws/eks-cluster/variables.tf
Add ArgoCD IAM role and aws auth CM entry
https://mattermost.atlassian.net/browse/CLD-4952
```release-note
- Add ArgoCD IAM role and aws auth CM entry to eks-cluster
```
> Add ArgoCD IAM role and aws auth CM entry

- aws/cluster/argocd_iam.tf
- aws/eks-cluster/argocd_iam.tf
Add conditional to ArgoCD Deployer creation for cross region conflicts
https://mattermost.atlassian.net/browse/CLD-5036
```release-note
- Add conditional to ArgoCD Deployer creation for cross region conflicts
```
> Add conditional to ArgoCD Deployer creation for cross region conflicts

- aws/tempo/providers.tf
- aws/tempo/tempo_iam.tf
- aws/tempo/tempo_s3.tf
- aws/tempo/variables.tf
Add tempo S3 bucket and IAM user module
https://mattermost.atlassian.net/browse/CLD-5063
```release-note
- Add tempo S3 bucket and IAM user module
```
> Add tempo S3 bucket and IAM user module

- aws/tempo/providers.tf
Fix dependency version for tempo
https://mattermost.atlassian.net/browse/CLD-5063
```release-note
- Fix dependency version for tempo
```
> Fix dependency version for tempo

- aws/grafana/README.md
- aws/grafana/locals.tf
- aws/grafana/providers.tf
- aws/grafana/rds.tf
- aws/grafana/variables.tf
Issue: CLD-2237
https://mattermost.atlassian.net/browse/CLD-2237
```release-note
NONE
```
> Add RDS for grafana

- aws/aurora-cluster/rds.tf
- aws/grafana/rds.tf
Issue: CLD-5115
Fix length bug
https://mattermost.atlassian.net/browse/CLD-5115
```release-note
NONE
```
> Fix length bug

- aws/cluster/aws_auth_configmap.tf
- aws/cluster/variables.tf
- aws/eks-cluster/aws_auth_configmap.tf
- aws/eks-cluster/variables.tf
- Replace the atlantis user with a specific env variable
```release-note
- Replace the atlantis user with a specific env variable
```
> Replace the atlantis user with a specific env variable

- aws/cluster/variables.tf
- aws/cluster/worker_asg.tf
- Add dedicated variable for EKS managed node group subnets
> [CLD-5210] Add dedicated variable for EKS managed node group subnets

- aws/cluster/variables.tf
- aws/cluster/worker_asg.tf
> Revert changes

- aws/eks-cluster/worker_iam.tf
Add eks-cluster worker role to support loki and cluster-autoscaler
https://mattermost.atlassian.net/browse/CLD-5283
https://mattermost.atlassian.net/browse/CLD-5284
```release-note
- Add eks-cluster worker role to support loki and cluster-autoscaler
```
> Add eks-cluster worker role

- aws/calls-offloader/README.md
- aws/calls-offloader/main.tf
- aws/calls-offloader/variables.tf
Add calls offloader module
```release-note
- Add calls offloader module
```
> Add calls offloader module

- aws/calls-offloader/main.tf
- aws/calls-offloader/variables.tf
Add root volume, and key pair to calls offloader
```release-note
- Add root volume, and key pair to calls offloader
```
> Add root volume, and key pair to calls offloader

- aws/subnet-and-networking-3az/nat_gtw.tf
- aws/subnet-and-networking-3az/route_tables.tf
- aws/subnet-and-networking-3az/variables.tf
- aws/subnet-and-networking-4az/nat_gtw.tf
- aws/subnet-and-networking-4az/route_tables.tf
- aws/subnet-and-networking-4az/variables.tf
- aws/subnet-and-networking/nat_gtw.tf
- aws/subnet-and-networking/route_tables.tf
- aws/subnet-and-networking/variables.tf
- Add logic  to be able to provision separate nat gateways per subnet
```release-note
- Add logic  to be able to provision separate nat gateways per subnet
```
> [CLD-5258] Add logic  to be able to provision separate nat gateways per subnet

- aws/calls-offloader/main.tf
- aws/calls-offloader/networking.tf
- aws/calls-offloader/variables.tf
Add ASG and LB to calls offloader
```release-note
- Add ASG and LB to calls offloader
```
> Add ASG and LB to calls offloader

- aws/subnet-and-networking-3az/security_groups.tf
- aws/subnet-and-networking-3az/variables.tf
- aws/subnet-and-networking-4az/security_groups.tf
- aws/subnet-and-networking-4az/variables.tf
- aws/subnet-and-networking/security_groups.tf
- aws/subnet-and-networking/variables.tf
Added SG rule to allow access between GitLab & DB
https://mattermost.atlassian.net/browse/CLD-5306
```release-note
Added SG rule to allow access between GitLab & DB
```
> Added SG rule to allow access between gitlab & DB

- aws/calls-offloader/main.tf
- aws/calls-offloader/variables.tf
Add calls-offloader VPC access to load balancer
```release-note
- Add calls-offloader VPC access to load balancer
```
> Add calls-offloader VPC access to load balancer

- aws/eks-managed-node-groups/spot_node_groups.tf
- aws/eks-managed-node-groups/variables.tf
Make spot nodes conditional
https://mattermost.atlassian.net/browse/CLD-5357
```release-note
- Make spot nodes conditional in EKS
```
> Make spot nodes conditional

- aws/calls-offloader/main.tf
Replace launch config with launch template for calls offloader
https://mattermost.atlassian.net/browse/CLD-5391
```release-note
- Replace launch config with launch template for calls offloader
```
> Replace launch config with launch template for calls offloader

- .tflint.hcl
- aws/iam-user/README.md
- aws/iam-user/main.tf
- aws/iam-user/outputs.tf
- aws/iam-user/variables.tf
- aws/iam-user/versions.tf
- aws/transit-gateway-attachment/README.md
- aws/transit-gateway-attachment/main.tf
- aws/transit-gateway-attachment/outputs.tf
- aws/transit-gateway-attachment/variables.tf
- aws/transit-gateway-attachment/versions.tf
- aws/vpc-route-tgw/README.md
- aws/vpc-route-tgw/main.tf
- aws/vpc-route-tgw/outputs.tf
- aws/vpc-route-tgw/variables.tf
- aws/vpc-route-tgw/versions.tf
- Added modules from [release-iac-modules](https://github.com/mattermost/release-iac-modules) repo
- Introduce new IAM user module to create AWS users for CI purposes with granular permissions
https://github.com/mattermost/release-iac/pull/36
```release-note
incorporate release iac modules
```
> Introduce release iac modules

- aws/cluster/README.md
- aws/cluster/variables.tf
- aws/cluster/worker_asg.tf
- aws/eks-cluster/README.md
- aws/eks-cluster/variables.tf
- aws/eks-cluster/worker_asg.tf
Add variable for disabling spot nodes for kube clusters
https://mattermost.atlassian.net/browse/CLD-5357
```release-note
- Add variable for disabling spot nodes for kube clusters
```
> Add variable for disabling spot nodes for kube clusters

- aws/calls-offloader/main.tf
- aws/calls-offloader/networking.tf
- aws/calls-offloader/variables.tf
Add multiple subnet IDs to ASG for calls offloader
https://mattermost.atlassian.net/browse/CLD-5361
```release-note
- Add multiple subnet IDs to ASG for calls offloader
```
> Add multiple subnet IDs to ASG for calls offloader

- aws/customer-web-server/README.md
- aws/customer-web-server/variables.tf
- aws/customer-web-server/web-server.tf
Issue: CLD-5471
Add support for stitch bastion to CWS
https://mattermost.atlassian.net/browse/CLD-5471
```release-note
NONE
```
> Add support for stitch bastion to CWS

- aws/cloud-lambda-storage/README.md
- aws/cloud-lambda-storage/iam.tf
- aws/cloud-lambda-storage/providers.tf
- aws/cloud-lambda-storage/s3.tf
- aws/cloud-lambda-storage/variables.tf
Add cloud lambda bucket storage
https://mattermost.atlassian.net/browse/CLD-5088
```release-note
- Add cloud lambda bucket storage
```
> Add cloud lambda bucket storage

- aws/iam-user/versions.tf
- aws/transit-gateway-attachment/versions.tf
- aws/vpc-route-tgw/versions.tf
Upgrade Terraform minimum versions to 1.1.8
https://mattermost.atlassian.net/browse/CLD-5480
```release-note
- Upgrade Terraform minimum versions to 1.1.8
```
> Upgrade Terraform minimum versions to 1.1.8

- aws/snapshot-status-alert/README.md
- aws/snapshot-status-alert/providers.tf
- aws/snapshot-status-alert/snapshot-status-alert.tf
-  Add module to track failures in EBS snapshots
> [CLD-3996] Add module to track failures in EBS snapshots

- aws/aurora-cluster/README.md
- aws/aurora-cluster/rds.tf
- aws/aurora-cluster/variables.tf
- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/awat/variables.tf
- aws/blapi/README.md
- aws/blapi/rds.tf
- aws/blapi/variables.tf
- aws/customer-web-server/README.md
- aws/customer-web-server/variables.tf
- aws/customer-web-server/web-server.tf
- aws/elrond/README.md
- aws/elrond/elrond-db.tf
- aws/elrond/variables.tf
- aws/grafana/README.md
- aws/grafana/rds.tf
- aws/grafana/variables.tf
- aws/provisioner/README.md
- aws/provisioner/provisioner-db.tf
- aws/provisioner/variables.tf
Issue: CLD-5492
Make aurora cluster module configurable to be able to not having readers
https://mattermost.atlassian.net/browse/CLD-5492
```release-note
NONE
```
> Make aurora cluster module configurable to be able to not having readers

- aws/velero/README.md
- aws/velero/variables.tf
- aws/velero/velero_iam.tf
IRSA IAM Setup for Velero
https://mattermost.atlassian.net/browse/CLD-5496
```release-note
IRSA IAM Setup for Velero
```
> IRSA Configuration for Velero

- aws/cluster/master.tf
- aws/cluster/providers.tf
Added OIDC IAM Provider for EKS cluster
https://mattermost.atlassian.net/browse/CLD-5506
```release-note
Added OIDC IAM Provider for EKS cluster
```
> Added OIDC IAM Provider for EKS cluster

- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/blapi/README.md
- aws/blapi/rds.tf
- aws/customer-web-server/README.md
- aws/customer-web-server/variables.tf
- aws/customer-web-server/web-server.tf
- aws/elrond/README.md
- aws/elrond/elrond-db.tf
- aws/grafana/README.md
- aws/grafana/rds.tf
- aws/provisioner/README.md
- aws/provisioner/provisioner-db.tf
Issue: CLD-5508
Add ability to disable bastion host CWS
https://mattermost.atlassian.net/browse/CLD-5508
```release-note
NONE
```
> Add ability to disable bastion host CWS

- aws/cloudwatch-event-alerts/README.md
- aws/cloudwatch-event-alerts/cloudwatch-event-alerts.tf
- aws/cloudwatch-event-alerts/providers.tf
- aws/cloudwatch-event-alerts/variables.tf
- aws/snapshot-status-alert/snapshot-status-alert.tf
- Add lambda function to handle all Cloudwatch event alerts via SNS
> [CLD-5510] Add lambda function to handle all Cloudwatch event alerts via SNS

- aws/iam-custom-resources/db_disaster_recovery.tf
Added KMS Permission for db_disaster_recovery user
https://mattermost.atlassian.net/browse/CLD-5536
```release-note
Added KMS Permission for db_disaster_recovery user
```
> Added KMS permission for DB recovery policy

- aws/iam-custom-resources/local.tf
Minor fix for secret manager ARN construction used by DR user
https://mattermost.atlassian.net/browse/CLD-5536
```release-note
Minor fix for secret manager ARN construction used by DR user
```
> Minor fix for secret manager ARN construction used by DR user

- aws/cluster/README.md
- aws/cluster/master.tf
Add VpcID tag to EKS cluster
Fixes https://mattermost.atlassian.net/browse/CLD-5438
```release-note
none
```
> [CLD-5438]Add VpcID tag to eks cluster

- aws/cluster/README.md
- aws/cluster/providers.tf
- aws/cluster/storage_class.tf
- aws/cluster/variables.tf
Add gp3 StorageClass
Fixes https://mattermost.atlassian.net/browse/CLD-2216
```release-note
Add StorageClass for type gp3
```
> [CLD-2216]Add gp3 storageclass

- aws/cluster/worker_asg.tf
- aws/eks-managed-node-groups/node_groups.tf
- aws/eks-managed-node-groups/spot_node_groups.tf
- aws/eks-managed-node-groups/variables.tf
Add VpcID tag to node instances
Fixes https://mattermost.atlassian.net/browse/CLD-5438
```release-note
none
```
> [CLD-5438]Add VpcID tag

- aws/cluster/README.md
- aws/cluster/worker_asg.tf
- aws/eks-managed-node-groups/README.md
- aws/eks-managed-node-groups/providers.tf
This will update eks-managed-groups version and kubernetes provider version.
```release-note
Upgrade kubernetes provider to 2.7.1
```
> [CLD-5438]update eks managed group version

- aws/eks-cluster/master.tf
- aws/eks-cluster/providers.tf
Added OIDC IAM for EKS cluster module to facilitate IRSA configuration 
https://mattermost.atlassian.net/browse/CLD-5555
```release-note
Added OIDC IAM for EKS cluster module to facilitate IRSA configuration
```
> Added OIDC IAM for EKS cluster module

- aws/aurora-cluster/cloudwatch.tf
- aws/aurora-cluster/variables.tf
- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/blapi/README.md
- aws/blapi/rds.tf
- aws/customer-web-server/README.md
- aws/customer-web-server/web-server.tf
- aws/elrond/README.md
- aws/elrond/elrond-db.tf
- aws/grafana/README.md
- aws/grafana/rds.tf
- aws/provisioner/README.md
- aws/provisioner/provisioner-db.tf
Issue: CLD-5565
Add alerting to aurora cluster module
https://mattermost.atlassian.net/browse/CLD-5565
```release-note
NONE
```
> Add alerting to aurora cluster module

- aws/rds-global-cluster/global-db-cluster.tf
Issue: CLD-5584
Add missing variables
https://mattermost.atlassian.net/browse/CLD-5584
```release-note
NONE
```
> Add missing variables

- aws/cluster/README.md
- aws/cluster/providers.tf
- aws/cluster/storage_class.tf
- aws/cluster/variables.tf
Reverts mattermost/mattermost-cloud-monitoring#578
> Revert "Revert "[CLD-2216]Add gp3 storageclass""

- aws/cluster/README.md
- aws/cluster/worker_asg.tf
- aws/eks-managed-node-groups/README.md
- aws/eks-managed-node-groups/providers.tf
Reverts mattermost/mattermost-cloud-monitoring#577
> Revert "Revert "[CLD-5438]update eks managed group version""

- aws/eks-managed-node-groups/node_groups.tf
Fix VpcID tag name
```release-note
None
```
> [CLD-5438]Fix vpcID tag name

- aws/rds-global-cluster/global-db-cluster.tf
- aws/rds-global-cluster/variables.tf
Issue: CLD-5600, CLD-5595
https://mattermost.atlassian.net/browse/CLD-5600
https://mattermost.atlassian.net/browse/CLD-5595
```release-note
NONE
```
> Improvements to rds-global-cluster module

- aws/rds-global-cluster/global-db-cluster.tf
- aws/rds-global-cluster/variables.tf
Issue: CLD-5600
More fixes to RDS global cluster
https://mattermost.atlassian.net/browse/CLD-5600
```release-note
NONE
```
> More fixes to RDS global cluster

- aws/rds-global-cluster/README.md
- aws/rds-global-cluster/global-db-cluster.tf
Issue: CLD-5600
Fix global cluster storage
```release-note
NONE
```
> Fix global cluster storage

- aws/transit-gateway-setup/tgw.tf
- aws/transit-gateway-setup/variables.tf
Add manual attachments and routes to tgw setup module
https://mattermost.atlassian.net/browse/CLD-5609
```release-note
- Add manual attachments and routes to tgw setup module
```
> Add manual attachments and routes to tgw setup module

- aws/transit-gateway-setup/tgw.tf
- aws/transit-gateway-setup/variables.tf
TGW Setup VPC route added by default
https://mattermost.atlassian.net/browse/CLD-5609
```release-note
- TGW Setup VPC route added by default
```
> TGW Setup VPC route added by default

- aws/subnet-and-networking-3az/nat_gtw.tf
- aws/subnet-and-networking-4az/nat_gtw.tf
- aws/subnet-and-networking/nat_gtw.tf
Add VpcID tag to nat gateways
Fixes https://mattermost.atlassian.net/browse/CLD-5437
```release-note
none
```
> [CLD-5437]Add VpcID tag to nat gateway

- aws/awat/awat_iam.tf
- aws/awat/awat_s3.tf
- aws/awat/variables.tf
> [CLD-5590] Move AWAT to IRSA

- aws/provisioner-users/README.md
- aws/provisioner-users/iam_role.tf
- aws/provisioner-users/variables.tf
Issue: CLD-5551
IRSA role for provisioner
https://mattermost.atlassian.net/browse/CLD-5551
```release-note
NONE
```
> IRSA role for provisioner

- aws/subnet-and-networking-3az/vpc_endpoint.tf
- aws/subnet-and-networking-4az/vpc_endpoint.tf
- aws/subnet-and-networking/vpc_endpoint.tf
- aws/vpc-endpoint/README.md
- aws/vpc-endpoint/providers.tf
- aws/vpc-endpoint/variables.tf
- aws/vpc-endpoint/vpc_endpoint.tf
- Add vpc S3 endpoint module and update existing subnet modules
> [CLD-5259] Add vpc S3 endpoint module and update existing subnet modules

- aws/mattermost-cloud-apps-deployer/iam.tf
- aws/mattermost-cloud-apps-deployer/providers.tf
- aws/mattermost-cloud-apps-deployer/variables.tf
Add mattermost-cloud-apps-deployer module
https://mattermost.atlassian.net/browse/CLD-5553
```release-note
- Add mattermost-cloud-apps-deployer module
```
> Add mattermost-cloud-apps-deployer module

- aws/subnet-and-networking-3az/README.md
- aws/subnet-and-networking-3az/security_groups.tf
- aws/subnet-and-networking-3az/variables.tf
- aws/subnet-and-networking-4az/README.md
- aws/subnet-and-networking-4az/security_groups.tf
- aws/subnet-and-networking-4az/variables.tf
- aws/subnet-and-networking/README.md
- aws/subnet-and-networking/security_groups.tf
- aws/subnet-and-networking/variables.tf
Added SG rule to allow cross region access for community/customer DB
https://mattermost.atlassian.net/browse/CLD-5636
```release-note
Added SG rule to allow cross region access for community/customer DB
```
> Added SG rule to allow cross region access for community/customer DB

- aws/subnet-and-networking-3az/README.md
- aws/subnet-and-networking-3az/security_groups.tf
- aws/subnet-and-networking-3az/variables.tf
- aws/subnet-and-networking-4az/README.md
- aws/subnet-and-networking-4az/security_groups.tf
- aws/subnet-and-networking-4az/variables.tf
- aws/subnet-and-networking/README.md
- aws/subnet-and-networking/security_groups.tf
- aws/subnet-and-networking/variables.tf
> Remove cross region sg

- aws/vpc-endpoint/README.md
- aws/vpc-endpoint/variables.tf
- aws/vpc-endpoint/vpc_endpoint.tf
- Make module for endpoints region aware
> [CLD-5259] Make module for endpoints region aware

- aws/database-factory/README.md
- aws/database-factory/database_factory_user_permissions.tf
- aws/database-factory/variables.tf
Migrate dbfactory to use IRSA
Fixes https://mattermost.atlassian.net/browse/CLD-5721
```release-note
```
> [CLD-5721]Migrate dbfactory to use IRSA

- aws/provisioner-users/provisioner_user_permissions.tf
Add modifyListener permission to provisioner
https://mattermost.atlassian.net/browse/CLD-5795
```release-note
NONE
```
> Add modifyListener permission to provisioner

- aws/vpc-setup/cluster_nodes_iam.tf
Add modifyListener permission to our custom node policy
https://mattermost.atlassian.net/browse/CLD-5808
```release-note
NONE
```
> Add modifyListener permission to our custom node policy

- aws/aurora-cluster/README.md
- aws/aurora-cluster/cloudwatch.tf
- aws/aurora-cluster/rds.tf
- aws/aurora-cluster/variables.tf
- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/awat/variables.tf
- aws/blapi/README.md
- aws/blapi/rds.tf
- aws/blapi/variables.tf
- aws/customer-web-server/README.md
- aws/customer-web-server/variables.tf
- aws/customer-web-server/web-server.tf
- aws/elrond/README.md
- aws/elrond/elrond-db.tf
- aws/elrond/variables.tf
- aws/grafana/README.md
- aws/grafana/rds.tf
- aws/grafana/variables.tf
- aws/provisioner/README.md
- aws/provisioner/provisioner-db.tf
- aws/provisioner/variables.tf
Change SNS topic used
Change SNS topic used
Change aurora cluster module to be able to disable performance insights
https://mattermost.atlassian.net/browse/CLD-5637
https://mattermost.atlassian.net/browse/CLD-5509
```release-note
NONE
```
> Change SNS topic used

- .tflint.hcl
- aws/awat/awat_s3.tf
- aws/blapi/s3.tf
- aws/community-on-demand/provisioning_s3.tf
- aws/gitlab-runner/main.tf
- aws/loki/s3.tf
- aws/provisioner-users/state_bucket.tf
- aws/route53-registration/providers.tf
- aws/tempo/tempo_s3.tf
- aws/velero/velero_s3.tf
- aws/vpc-setup/installation_s3_buckets.tf
Issue: CLD-5830
Add versioning to provisioning buckets
Fix deprecated terraform resources regarding aws buckets
https://mattermost.atlassian.net/browse/CLD-5830
```release-note
NONE
```
> Add versioning to provisioning buckets

- aws/vpc-setup/installation_s3_buckets.tf
fix foreach in buckets config
https://mattermost.atlassian.net/browse/CLD-5830
```release-note
NONE
```
> fix foreach in buckets config

- aws/vpc-setup/installation_s3_buckets.tf
fix foreach 2
```release-note
NONE
```
> fix foreach 2

- aws/vpc-setup/installation_s3_buckets.tf
fix buckets naming
```release-note
NONE
```
> fix buckets naming

- aws/calls-offloader/main.tf
- aws/rds-global-cluster/global-db-cluster.tf
- aws/rds-global-cluster/variables.tf
Fix cloudwatch exports for community
Fix calls-offloader
https://mattermost.atlassian.net/browse/CLD-5895
https://mattermost.atlassian.net/browse/CLD-5896
```release-note
NONE
```
> Fix cloudwatch exports for community

- aws/awat/awat_s3.tf
- aws/loki/s3.tf
- aws/tempo/tempo_s3.tf
Make policy valid json
```release-note
NONE
```
> Make policy valid json

- aws/awat/awat_s3.tf
- aws/loki/s3.tf
- aws/tempo/tempo_s3.tf
Make policy string json instead of json object
```release-note
NONE
```
> Make policy string json instead of json object

- aws/awat/awat_s3.tf
- aws/loki/s3.tf
- aws/tempo/tempo_s3.tf
use count in s3 policies
```release-note
NONE
```
> use count in s3 policies

- aws/elasticsearch/README.md
- aws/elasticsearch/elasticsearch.tf
- aws/elasticsearch/variables.tf
Fix elasticsearch module to support audit logs
https://mattermost.atlassian.net/browse/CLD-5923
```release-note
NONE
```
> Fix elasticsearch module to support audit logs

- aws/bastion-host-stitch/ec2.tf
- aws/bastion-host-stitch/variables.tf
- aws/blapi/rds.tf
- aws/blapi/variables.tf
Refactor stitch module after blapi cleanup
https://mattermost.atlassian.net/browse/CLD-5962
```release-note
NONE
```
> Refactor stitch module after blapi cleanup

- aws/bastion-host-stitch/ec2.tf
Fix missing type
```release-note
NONE
```
> Fix missing type

- aws/provisioner-users/provisioner_user_permissions.tf
```release-note
Allow GetBucketVersioning for provisioner user
```
> Allow GetBucketVersioning for provisioner user

- aws/provisioner-users/provisioner_user_permissions.tf
Allow s3 PutBucketVersioning for provisioner-users
```release-note
NONE
```
> Allow s3 PutBucketVersioning for provisioner-users

- aws/iam-custom-resources/exports.tf
- aws/iam-custom-resources/variables.tf
-  Create exports IAM user for custom data exports
> [CLD-6014] Create exports IAM user for custom data exports

- aws/database-factory/database_factory_user_permissions.tf
Add missing permissions to database factory role
https://mattermost.atlassian.net/browse/CLD-6174
```release-note
NONE
```
> Add missing permissions to database factory role

- aws/atlantis/README.md
- aws/atlantis/atlantis.tf
- aws/bind-server/README.md
- aws/bind-server/bind-servers.tf
Remove LCs from atlantis and bind servers modules
https://mattermost.atlassian.net/browse/CLD-5678
```release-note
NONE
```
> Remove LCs from atlantis and bind servers modules

- aws/atlantis/atlantis.tf
- aws/bind-server/bind-servers.tf
Fix LT configuration
```release-note
NONE
```
> Fix LT configuration

- aws/vpc-setup/README.md
- aws/vpc-setup/installation_s3_buckets.tf
- aws/vpc-setup/variables.tf
Refactor VPC setup module to supprt custom KMS keys
https://mattermost.atlassian.net/browse/CLD-6196
```release-note
NONE
```
> Refactor VPC setup module to supprt custom KMS keys

- aws/vpc-setup/installation_s3_buckets.tf
VPC setup fixes
https://mattermost.atlassian.net/browse/CLD-6196
```release-note
NONE
```
> VPC setup fixes

- aws/vpc-setup/README.md
- aws/vpc-setup/installation_s3_buckets.tf
VPC setup fixes due to changed AWS defaults
https://mattermost.atlassian.net/browse/CLD-6196
```release-note
NONE
```
> VPC setup fixes due to changed AWS defaults

- aws/aurora-cluster/README.md
- aws/aurora-cluster/rds.tf
- aws/aurora-cluster/variables.tf
Add variable to customize the CA certificate in DB instances
https://mattermost.atlassian.net/browse/CLD-6348
```release-note
NONE
```
> Add variable to customize the CA certificate in DB instances

- aws/cloud-lambda-storage/s3.tf
Add Bucket ownership
Fixes https://mattermost.atlassian.net/browse/CLD-6405
-->
```release-note
NONE
```
> [CLD-6405]Add bucket ownership

- aws/provisioner-users/provisioner_user_permissions.tf
Fix bucket encryption permissions
https://mattermost.atlassian.net/browse/CLD-6389
```release-note
NONE
```
> Fix bucket encryption permissions

- aws/vpc-setup/kms.tf
Fix - Remove duplicate declaration
https://mattermost.atlassian.net/browse/CLD-6392
```release-note
NONE
```
> Fix - Remove duplicate declaration

- aws/rds-customer-cluster/README.md
- aws/rds-customer-cluster/main.tf
- aws/rds-customer-cluster/providers.tf
- aws/rds-customer-cluster/variables.tf
- aws/subnet-and-networking-3az/variables.tf
- aws/subnet-and-networking-3az/vpc_endpoint.tf
- aws/subnet-and-networking-4az/variables.tf
- aws/subnet-and-networking-4az/vpc_endpoint.tf
- aws/subnet-and-networking/variables.tf
- aws/subnet-and-networking/vpc_endpoint.tf
- aws/vpc-setup/installation_s3_buckets.tf
- Add support for networking in second region
- Add RDS module with global RDS support
```release-note
- Add support for networking in second region
- Add RDS module with global RDS support
```
> CLD-6439-6395 Add support for networking in second region and new RDS module with global RDS support

- aws/rds-customer-cluster/main.tf
- Fixes and improvements on rds module
```release-note
- Fixes and improvements on rds module
```
> [CLD-6258] Fixes and improvements on rds module

- aws/cleanup-unused-images/lambdas.tf
Migrate deckhand to new AWS runtime
https://mattermost.atlassian.net/browse/CLD-6500
```release-note
NONE
```
> Migrate deckhand to new AWS runtime

- aws/account-alerts/account_alerts.tf
- aws/cloudwatch-alarms/cloudwatch-alarms.tf
- aws/cloudwatch-event-alerts/cloudwatch-event-alerts.tf
- aws/ebs-janitor/ebs_janitor.tf
- aws/elb-cleanup/elb-cleanup-lambda.tf
- aws/grafana-aws-metrics/grafana-aws-metrics.tf
- aws/lambda-promtail/lambdas.tf
- aws/rds-cluster-events/rds-cluster.events.tf
- aws/server-auth/cloud-server-auth.tf
Update AWS lambda to use custom runtime
https://mattermost.atlassian.net/browse/CLD-6228
```release-note
NONE
```
> Update AWS lambda to use custom runtime

- aws/rds-customer-cluster/main.tf
- aws/rds-customer-cluster/variables.tf
- Add support for custom KMS keys for performance insights
```release-note
- Add support for custom KMS keys for performance insights
```
> [CLD-6358] Add support for custom KMS keys for performance insights

- aws/bind-server/bind-server-network-attachment.tf
Migrate bind attachment lambda to custom runtime
https://mattermost.atlassian.net/browse/CLD-6228
```release-note
NONE
```
> Migrate bind attachment lambda to custom runtime

- aws/velero/README.md
- aws/velero/velero_s3.tf
Remove acl as not needed
```release-note
NONE
```
> Remove acl as not needed

- aws/generic-webhook-notification/README.md
- aws/generic-webhook-notification/api-gateway.tf
- aws/generic-webhook-notification/lambdas.tf
- aws/generic-webhook-notification/providers.tf
- aws/generic-webhook-notification/variables.tf
Create module for generic-webhook-notification
https://mattermost.atlassian.net/browse/CLD-6607
```release-note
NONE
```
> Create module for generic-webhook-notification

- aws/generic-webhook-notification/README.md
- aws/generic-webhook-notification/lambdas.tf
- aws/generic-webhook-notification/variables.tf
Migrate generic-webhook-notification to module fixes
```release-note
NONE
```
> Migrate generic-webhook-notification to module fixes

- aws/generic-webhook-notification/iam.tf
- aws/generic-webhook-notification/lambdas.tf
Fix missing role
```release-note
NONE
```
> Fix missing role

- aws/generic-webhook-notification/README.md
- aws/generic-webhook-notification/lambdas.tf
- aws/generic-webhook-notification/variables.tf
Small changes to sync with existing resources
```release-note
NONE
```
> Small changes to sync with existing resources

- aws/generic-webhook-notification/api-gateway.tf
FIx API path
```release-note
NONE
```
> FIx API path

- aws/generic-webhook-notification/README.md
- aws/generic-webhook-notification/api-gateway.tf
- aws/generic-webhook-notification/variables.tf
Custom parent ID
```release-note
NONE
```
> Custom parent ID

- aws/rds-customer-cluster/main.tf
- aws/rds-customer-cluster/variables.tf
- Add support for different replicas across regions in global clusters
```release-note
- Add support for different replicas across regions in global clusters
```
> [CLD-6257] Add support for different replicas across regions in global clusters

- aws/rds-customer-cluster/main.tf
- aws/rds-customer-cluster/variables.tf
- Parameterise global database name
```release-note
- Parameterise global database name
```
> Parameterise global database name

- aws/rds-customer-cluster/README.md
- aws/rds-customer-cluster/main.tf
- aws/rds-customer-cluster/variables.tf
Add missing variable to RDS customer clusters
https://mattermost.atlassian.net/browse/CLD-6736
```release-note
NONE
```
> Add missing variable to RDS customer clusters

- aws/eks-cluster/README.md
- aws/eks-cluster/eks_addon.tf
Fix resolve conflicts on eks addons
https://mattermost.atlassian.net/browse/CLD-6757
```release-note
NONE
```
> Fix resolve conflicts on eks addons

- aws/eks-cluster/README.md
- aws/eks-cluster/variables.tf
- aws/eks-cluster/worker_asg.tf
- aws/eks-managed-node-groups/README.md
- aws/eks-managed-node-groups/graviton_node_groups.tf
- aws/eks-managed-node-groups/variables.tf
Add support for seperate ARM/Graviton nodegroups
https://mattermost.atlassian.net/browse/CLD-6887
```release-note
NONE
```
> Add support for seperate ARM/Graviton nodegroups

- aws/cluster/README.md
- aws/cluster/variables.tf
- aws/cluster/worker_asg.tf
- aws/eks-cluster/worker_asg.tf
Add arm support to the other cluster module too
```release-note
NONE
```
> Add arm support to the other cluster module too

- aws/cluster/README.md
- aws/cluster/worker_asg.tf
- aws/eks-cluster/README.md
- aws/eks-cluster/worker_asg.tf
- aws/eks-managed-node-groups/graviton_node_groups.tf
Fix typo in eks managed arm nodegroup
```release-note
NONE
```
> Fix typo in eks managed arm nodegroup

- aws/bind-server/README.md
- aws/bind-server/bind-servers-arm.tf
- aws/bind-server/iam.tf
- aws/bind-server/network.tf
- aws/bind-server/variables.tf
Add ARM support to bind server module
https://mattermost.atlassian.net/browse/CLD-6973
```release-note
NONE
```
> Add ARM support to bind server module

- aws/bind-server/bind-servers-arm.tf
fix duplicate
```release-note
NONE
```
> fix duplicate

- aws/bind-server/README.md
- aws/bind-server/bind-server-network-attachment.tf
- aws/bind-server/bind-servers-arm.tf
- aws/bind-server/variables.tf
fixes for arm bind transition
```release-note
NONE
```
> fixes for arm bind transition

- aws/bind-server/README.md
- aws/bind-server/network.tf
add missing hook
```release-note
NONE
```
> add missing hook

- aws/iam-custom-resources/packer.tf
add missing permission to packer user
https://mattermost.atlassian.net/browse/CLD-6948
```release-note
NONE
```
> add missing permission to packer user

- aws/eks-cluster/worker_asg.tf
add missing vpc_id variable
```release-note
NONE
```
> add missing vpc_id variable

- aws/rds-customer-cluster/main.tf
Make parameter-group family dynamic
Fixes https://mattermost.atlassian.net/browse/CLD-6938
```release-note
```
> [CLD-6938]Make parameter-group family dynamic

- aws/rds-customer-cluster/main.tf
- aws/rds-customer-cluster/variables.tf
Add password_encryption and auth_method cluster parameters
Fixes https://mattermost.atlassian.net/browse/CLD-7211
```release-note
```
> [CLD-7211]Add password_encryption and auth_method cluster parameters

- aws/awat/README.md
- aws/awat/awat_s3.tf
- aws/awat/variables.tf
- aws/cluster/README.md
- aws/cluster/aws_auth_configmap.tf
- aws/cluster/variables.tf
- aws/loki/README.md
- aws/loki/s3.tf
- aws/loki/variables.tf
- aws/provisioner-users/README.md
- aws/provisioner-users/state_bucket.tf
- aws/provisioner-users/variables.tf
- aws/tempo/README.md
- aws/tempo/tempo_s3.tf
- aws/tempo/variables.tf
Remove cnc_user from modules because we're not using it and it doesn't exist in production
https://mattermost.atlassian.net/browse/CLD-7217
```release-note
remove cnc_user
```
> [CLD-7211]Remove cnc_user

- aws/awat/README.md
- aws/awat/awat_iam.tf
- aws/awat/awat_s3.tf
- aws/awat/variables.tf
- aws/loki/s3.tf
- aws/tempo/tempo_s3.tf
Fix awat s3 permission and remove old cnc-user conditions from policy
Fixes https://mattermost.atlassian.net/browse/CLD-7218
```release-note
none
```
> [CLD-7218]Fix awat s3 permission

- aws/cluster/eks_addon.tf
remove deprecated argument eks addon
https://mattermost.atlassian.net/browse/CLD-7262
```release-note
NONE
```
> remove deprecated argument eks addon

- aws/generic-webhook-notification/lambdas.tf
- aws/generic-webhook-notification/variables.tf
- Fix environment variable for Pagerduty Integration
```release-note
- Fix environment variable for Pagerduty Integration
```
> [CLD-7437] Fix environment variable for Pagerduty Integration

- aws/elrond/README.md
- aws/elrond/elrond-db.tf
Fix aurora tag
```release-note
none
```
> Fix aurora tag

- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/awat/variables.tf
This PR is going to add a few parameters to be able to upgrade AWAT RDS
Fixes https://mattermost.atlassian.net/browse/CLD-6935
```release-note
none
```
> [CLD-6935]Fix awat database upgrade

- aws/cluster/worker_iam.tf
- aws/loki/s3.tf
- aws/loki/variables.tf
- aws/route53-registration/route53.tf
- aws/route53-registration/variables.tf
- Add bucket and permissions for loki developers bucket
```release-note
- Add bucket and permissions for loki developers bucket
```
> CLD-7366 Add bucket and permissions for loki developers bucket

- aws/loki/s3.tf
- Fix bucket name for Loki
```release-note
- Fix bucket name for Loki
```
> Fix bucket name for Loki

- aws/external-secrets/README.md
- aws/external-secrets/providers.tf
update required terraform to external-secrets
https://mattermost.atlassian.net/browse/CLD-7514
```release-note
NONE
```
> update required terraform to external-secrets

- aws/external-secrets/iam.tf
Update external-secrets permissions
https://mattermost.atlassian.net/browse/CLD-7529
```release-note
NONE
```
> Update external-secrets module

- aws/external-secrets/iam.tf
fix external-secrets module to avoid overwrites
https://mattermost.atlassian.net/browse/CLD-7530
```release-note
NONE
```
> fix external-secrets module to avoid overwrites

- aws/external-secrets/README.md
- aws/external-secrets/iam.tf
- aws/external-secrets/variables.tf
Simplify external-secrets module
```release-note
NONE
```
> Simplify external-secrets module

- aws/provisioner-users/provisioner_user_permissions.tf
Add permissions for kops 1.28
https://mattermost.atlassian.net/browse/CLD-7601
```release-note
NONE
```
> Add permissions for kops 1.28

- aws/provisioner-users/provisioner_user_permissions.tf
add one more permission
```release-note
NONE
```
> add one more permission

- aws/generic-webhook-notification/lambdas.tf
try to fix core lambdas tagging
https://mattermost.atlassian.net/browse/CLD-7664
```release-note
NONE
```
> try to fix core lambdas

- aws/bind-server/README.md
- aws/bind-server/network.tf
- aws/bind-server/variables.tf
Make heartbeat timeout variable
https://mattermost.atlassian.net/browse/CLD-7858
```release-note
NONE
```
> Make heartbeat timeout variable

- aws/iam-custom-resources/README.md
- aws/iam-custom-resources/packer.tf
Add missing packer user permissions
https://mattermost.atlassian.net/browse/CLD-7868
```release-note
NONE
```
> Add missing packer user permissions

- aws/awat/variables.tf
- aws/customer-web-server/variables.tf
- aws/customer-web-server/web-server.tf
- aws/elrond/variables.tf
- aws/provisioner/provisioner-db.tf
- aws/provisioner/variables.tf
This PR will prepare to upgrade RDS for cws and provisioner
Fixes https://mattermost.atlassian.net/browse/CLD-7967
```release-note
NONE
```
> [CLD-7967] Upgrade cws and provisioner RDS

- aws/customer-web-server/README.md
- aws/customer-web-server/variables.tf
- aws/provisioner/README.md
- aws/provisioner/variables.tf
Add default value to allow upgrade
https://mattermost.atlassian.net/browse/CLD-7981
```release-note
NONE
```
> Add default value to allow upgrade

- aws/iam-custom-resources/packer.tf
add more missing permissions for packer
https://mattermost.atlassian.net/browse/CLD-7980
```release-note
NONE
```
> add more missing permissions for packer

- aws/cluster/README.md
- aws/cluster/variables.tf
- aws/iam-custom-resources/packer.tf
Add missing permissions to packer
https://mattermost.atlassian.net/browse/CLD-8098
```release-note
NONE
```
> Add missing permissions to packer

- aws/debug-caller-identity/output.tf
- aws/debug-caller-identity/providers.tf
- aws/debug-caller-identity/variables.tf
debug caller identity
https://mattermost.atlassian.net/browse/CLD-8089
```release-note
NONE
```
> debug caller identity

- aws/provisioner-users/README.md
- aws/provisioner-users/iam_role.tf
Add missing permissions to IRSA provisioner role
https://mattermost.atlassian.net/browse/CLD-8192
```release-note
NONE
```
> Add missing permissions to IRSA provisioner role

- aws/provisioner-users/iam_role.tf
- aws/provisioner-users/provisioner_user_permissions.tf
fix permissions
```release-note
NONE
```
> fix permissions

- aws/provisioner-users/iam_role.tf
attach only when enabled
```release-note
NONE
```
> attach only when enabled

- aws/pexip/cloudflare.tf
- aws/pexip/ec2.tf
- aws/pexip/providers.tf
- aws/pexip/sg.tf
- aws/pexip/variables.tf
Deployment Pexip Infinity management and conference standalone instances
https://mattermost.atlassian.net/browse/CLD-7884
```release-note
Deployment Pexip Infinity management and conference standalone instances
```
> Deployment Pexip Infinity management and conference standalone instances

- aws/mattermost-teams-tab/README.md
- aws/mattermost-teams-tab/main.tf
Adding mattermost-teams-tab user with bucket credentails
```release-note
None
```
> [CLD-8296]Add mattermost-teams-tab user

- aws/mattermost-teams-tab/README.md
- aws/mattermost-teams-tab/main.tf
- aws/mattermost-teams-tab/variables.tf
Adding cloudfront In front of s3 bucket
```release-note
Adding cloudfront for teams-tab
```
> [CLD-8296]Add teams-tab cloudfront

- aws/mattermost-teams-tab/main.tf
Fix cloudfront domain name variable
```release-note
None
```
> [CLD-8296]Fix cf domain name

- aws/mattermost-teams-tab/README.md
- aws/mattermost-teams-tab/main.tf
- aws/mattermost-teams-tab/variables.tf
Fix cf origin identity
```release-note
None
```
> [CLD-8296]Fix cf origin identity

- aws/cluster-autoscaler/README.md
- aws/cluster-autoscaler/iam.tf
- aws/cluster-autoscaler/providers.tf
- aws/cluster-autoscaler/variables.tf
Add cluster-autoscaler IRSA module
[
](https://mattermost.atlassian.net/browse/CLD-8299)#### Release Note
```release-note
NONE
```
> Add cluster-autoscaler IRSA module

- aws/cluster-autoscaler/README.md
- aws/cluster-autoscaler/iam.tf
- aws/cluster-autoscaler/variables.tf
Be able to attach policy in existing role too
https://mattermost.atlassian.net/browse/CLD-8306
```release-note
NONE
```
> Be able to attach policy in existing role too

- aws/cross-account-private-link-eks-private-source-account/README.md
- aws/cross-account-private-link-eks-private-source-account/providers.tf
- aws/cross-account-private-link-eks-private-source-account/variables.tf
- aws/cross-account-private-link-eks-private-target-account/README.md
- aws/cross-account-private-link-eks-private-target-account/providers.tf
- aws/cross-account-private-link-eks-private-target-account/variables.tf
- aws/cross-account-private-link-service-source-account/README.md
- aws/cross-account-private-link-service-source-account/providers.tf
- aws/cross-account-private-link-service-source-account/variables.tf
- aws/cross-account-private-link-service-target-account/README.md
- aws/cross-account-private-link-service-target-account/providers.tf
- aws/cross-account-private-link-service-target-account/variables.tf
Remove unneeded variables and use aws_caller_identity instead
https://mattermost.atlassian.net/browse/CLD-8313
```release-note
NONE
```
> Remove unneeded variables and use aws_caller_identity instead

- aws/cross-account-private-link-eks-private-source-account/README.md
- aws/cross-account-private-link-eks-private-source-account/iam.tf
- aws/cross-account-private-link-eks-private-source-account/variables.tf
- aws/cross-account-private-link-eks-private-target-account/README.md
- aws/cross-account-private-link-eks-private-target-account/iam.tf
- aws/cross-account-private-link-eks-private-target-account/main.tf
- aws/cross-account-private-link-eks-private-target-account/variables.tf
- aws/cross-account-private-link-service-source-account/README.md
- aws/cross-account-private-link-service-source-account/iam.tf
- aws/cross-account-private-link-service-source-account/main.tf
- aws/cross-account-private-link-service-source-account/variables.tf
- aws/cross-account-private-link-service-target-account/README.md
- aws/cross-account-private-link-service-target-account/iam.tf
- aws/cross-account-private-link-service-target-account/variables.tf
POC Private link modules fixes
```release-note
NONE
```
> POC Private link modules fixes

- aws/cross-account-private-link-eks-private-source-account/providers.tf
- aws/cross-account-private-link-eks-private-target-account/providers.tf
- aws/cross-account-private-link-service-source-account/providers.tf
- aws/cross-account-private-link-service-target-account/providers.tf
don't assume role upon resources creation
```release-note
NONE
```
> don't assume role upon resources creation

- aws/cross-account-private-link-eks-private-target-account/main.tf
- aws/cross-account-private-link-service-source-account/main.tf
Fix NLB issue
```release-note
NONE
```
> Fix NLB issue

- aws/cross-account-private-link-eks-private-target-account/README.md
- aws/cross-account-private-link-eks-private-target-account/main.tf
- aws/cross-account-private-link-eks-private-target-account/variables.tf
- aws/cross-account-private-link-service-source-account/README.md
- aws/cross-account-private-link-service-source-account/main.tf
- aws/cross-account-private-link-service-source-account/variables.tf
Fix errors on checks for existing NLBs or EKS clusters
```release-note
NONE
```
> Fix errors on checks for existing NLBs or EKS clusters

- aws/cross-account-private-link-eks-private-source-account/main.tf
- aws/cross-account-private-link-service-target-account/main.tf
Fix VPC_endpoint_type
```release-note
NONE
```
> Fix VPC_endpoint_type

- aws/cross-account-private-link-eks-private-target-account/README.md
- aws/cross-account-private-link-eks-private-target-account/main.tf
- aws/cross-account-private-link-eks-private-target-account/variables.tf
- aws/cross-account-private-link-service-source-account/README.md
- aws/cross-account-private-link-service-source-account/main.tf
- aws/cross-account-private-link-service-source-account/variables.tf
Fixes after testing everything
```release-note
NONE
```
> Fixes after testing everything

- aws/eks-customer/example/variables.tf
- Replace Promtail with Alloy
```release-note
- Replace Promtail with Alloy
```
> [CLD-8352] Replace Promtail with Alloy

- aws/eks-customer/README.md
- aws/eks-customer/versions.tf
Bump terraform version to 1.9 for eks-customer module to keep in sync with latest atlantis terraform support
```release-note
Bump terraform version to 1.9 for eks-customer
```
> bump tf version for eks-customer module

- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/awat/variables.tf
- aws/customer-web-server/README.md
- aws/customer-web-server/variables.tf
- aws/customer-web-server/web-server.tf
- aws/elrond/README.md
- aws/elrond/elrond-db.tf
- aws/elrond/variables.tf
- aws/provisioner/README.md
- aws/provisioner/provisioner-db.tf
- aws/provisioner/variables.tf
- aws/rds-customer-cluster/README.md
- aws/rds-customer-cluster/main.tf
- aws/rds-customer-cluster/variables.tf
Bump aurora-cluster plugin to all internal services' RDS clusters
https://mattermost.atlassian.net/browse/CLD-8387
```release-note
NONE
```
> Bump aurora-cluster plugin to all internal services' RDS clusters

- aws/eks-customer/README.md
- aws/eks-customer/eks.tf
- aws/eks-customer/scripts/utils.sh
- aws/eks-customer/variables.tf
- Fix git config to make it only for gitops repo.
- Add Atlantis user to be able to access eks.
https://mattermost.atlassian.net/browse/CLD-8383
```release-note
None
```
> Fix git config

- aws/rds-customer-cluster/README.md
- aws/rds-customer-cluster/variables.tf
Adding default value for accepted_password_auth_method
Fixes https://mattermost.atlassian.net/browse/CLD-8405
```release-note
None
```
> Adding default value for accepted_password_auth_method

- aws/import-export/README.md
- aws/import-export/kms.tf
- aws/import-export/s3.tf
- aws/import-export/variables.tf
Fixes in Import IaC during sync with reality
https://mattermost.atlassian.net/browse/CLD-8263
```release-note
NONE
```
> Fixes in Import IaC during sync with reality

- aws/eks-customer/README.md
- aws/eks-customer/eks_managed_node-group.tf
- aws/eks-customer/variables.tf
This PR will attach a new I am policy to nodes to perform ec2 volume operations
Fixes https://mattermost.atlassian.net/browse/CLD-8407
```release-note
None
```
> adding ec2 volume policies to nodes

- aws/eks-customer/scripts/deploy-utility.sh
Do not override custom-values if file already exists
Fixes https://mattermost.atlassian.net/browse/CLD-8407
```release-note
None
```
> CLD-8407: skip override custom values if file exists

- aws/eks-customer/example/main.tf
- aws/eks-customer/example/variables.tf
- aws/redis/README.md
- aws/redis/main.tf
- aws/redis/variables.tf
- aws/redis/versions.tf
- Add Terraform module for Redis Elasticache cluster deployments
```release-note
- Add Terraform module for Redis Elasticache cluster deployments
```
> [CLD-8410] Add Terraform module for Redis Elasticache cluster deployments

- aws/redis/README.md
- aws/teleport-databases/README.md
- aws/teleport-databases/iam.tf
- aws/teleport-databases/variables.tf
Fix teleport databases role definition
```release-note
NONE
```
> Fix teleport databases role definition

- aws/s3-data/README.md
- aws/s3-data/main.tf
- aws/s3-data/providers.tf
- aws/s3-data/variables.tf
- Add support for data S3 bucket/IAM user
```release-note
- Add support for data S3 bucket/IAM user
```
> Add support for data S3 bucket/IAM user

- aws/s3-data/main.tf
- Fix bucket policy
```release-note
- Fix bucket policy
```
> Fix bucket policy

- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/customer-web-server/README.md
- aws/customer-web-server/web-server.tf
- aws/elrond/README.md
- aws/elrond/elrond-db.tf
- aws/provisioner/README.md
- aws/provisioner/provisioner-db.tf
Bump aurora-cluster module in internal services
https://mattermost.atlassian.net/browse/CLD-8484
```release-note
NONE
```
> Bump aurora-cluster module in internal services

- aws/eks-customer/scripts/deploy-utility.sh
This will fix the `hostNetwork` replace sed command
```release-note
None
```
> Fix utility custom values replace command

- aws/eks-customer/eks_managed_node-group.tf
Add labels option to node groups
Fixes https://mattermost.atlassian.net/browse/CLD-8501
```release-note
None
```
> CLD-8501: add labels to node group

- aws/subnet-and-networking/README.md
- aws/subnet-and-networking/variables.tf
Fix duplicated variable
```release-note
NONE
```
> Fix duplicated variable

- aws/subnet-and-networking-3az/route_tables.tf
- aws/subnet-and-networking-3az/variables.tf
- aws/subnet-and-networking-4az/route_tables.tf
- aws/subnet-and-networking-4az/variables.tf
- aws/subnet-and-networking/route_tables.tf
- aws/subnet-and-networking/variables.tf
- aws/transit-gateway/tgw_attachment.tf
- aws/transit-gateway/variables.tf
CLD-8564 Fix all route table routes to allow multi CIDR entries
```release-note
- Fix all route table routes to allow multi CIDR entries
```
> CLD-8564 Fix all route table routes to allow multi CIDR entries

- aws/grant-privileges-to-schemas/README.md
- aws/grant-privileges-to-schemas/example/main.tf
- aws/grant-privileges-to-schemas/grant-privileges-to-schemas.tf
- aws/grant-privileges-to-schemas/providers.tf
- aws/grant-privileges-to-schemas/terraform.tfvars.sample
- aws/grant-privileges-to-schemas/variables.tf
- aws/subnet-and-networking-3az/README.md
- aws/subnet-and-networking-4az/README.md
- aws/subnet-and-networking/README.md
- aws/transit-gateway/README.md
Grant privileges lambda infra
https://mattermost.atlassian.net/browse/CLD-8526
```release-note
NONE
```
> Grant privileges lambda infra

- aws/eks-customer/README.md
- aws/eks-customer/eks_managed_node-group.tf
- aws/eks-customer/variables.tf
Adding Disk Block to managed nodes
Fixes https://mattermost.atlassian.net/browse/CLD-8604
```release-note
Adding disk block to managed node group in EKS module
```
> Adding Disk Block to managed nodes

- aws/eks-customer/scripts/deploy-utility.sh
- aws/eks-customer/utility.tf
Adding AWS_ACCOUNT field to use in utility custom values
https://mattermost.atlassian.net/browse/CLD-8624
```release-note
None
```
> [CLD-8624]: Adding AWS_ACCOUNT field to use in utility custom values

- aws/eks-customer/README.md
- aws/eks-customer/eks_managed_node-group.tf
- aws/eks-customer/irsa.tf
- aws/eks-customer/utility_policies.tf
- Add external-secrets to use IRSA
- Fix network_interfaces
- Enable public_subnets for nodes like calls
https://mattermost.atlassian.net/browse/CLD-8617
```release-note
None
```
> CLD-8617: Fixes some issues for node groups

- aws/calls-offloader-storage/README.md
- aws/calls-offloader-storage/efs.tf
- aws/calls-offloader-storage/nfs.tf
- aws/eks-customer/README.md
EFS configuration fixes
```release-note
NONE
```
> EFS configuration fixes

- aws/vpc-setup/cluster_nodes_iam.tf
Add efs missing permissions to node policy
https://mattermost.atlassian.net/browse/CLD-8692
```release-note
NONE
```
> Add efs missing permissions to node policy

- aws/cluster/README.md
- aws/cluster/locals.tf
- aws/cluster/master.tf
- aws/cluster/variables.tf
- aws/cluster/worker_asg.tf
- aws/eks-managed-node-groups/README.md
- aws/eks-managed-node-groups/graviton_node_groups.tf
- aws/eks-managed-node-groups/node_groups.tf
- aws/eks-managed-node-groups/variables.tf
Add AL2023 support to eks CNC clusters
https://mattermost.atlassian.net/browse/CLD-8761
```release-note
NONE
```
> Add AL2023 support to eks CNC clusters

- aws/eks-customer/README.md
- aws/eks-customer/eks_managed_node-group.tf
- aws/eks-customer/eks_policies.tf
- aws/eks-customer/variables.tf
Add IAM policy for nodes.
Fixes https://mattermost.atlassian.net/browse/CLD-8693
```release-note
Adding self-contained IAM policies for nodes in eks-customer module
```
> CLD-8753: Add iam policy for nodes

- aws/eks-customer/README.md
- aws/eks-customer/eks.tf
- aws/eks-customer/variables.tf
Fix iam inline policy deprecation + update eks module
Fixes https://mattermost.atlassian.net/browse/CLD-8673
```release-note
Upgrade eks was module to version 20.31.6 in eks-customer
```
> CLD-8673: Fix iam inline policy deprecation + update eks module

- aws/cluster/README.md
- aws/cluster/worker_asg.tf
- aws/cluster/worker_iam.tf
- aws/eks-managed-node-groups/README.md
- aws/eks-managed-node-groups/graviton_node_groups.tf
- aws/eks-managed-node-groups/node_groups.tf
- aws/eks-managed-node-groups/providers.tf
Fixes to module to support AL2023
https://mattermost.atlassian.net/browse/CLD-8733
```release-note
NONE
```
> Fixes to module to support AL2023

- aws/cluster/README.md
- aws/cluster/worker_asg.tf
- aws/eks-managed-node-groups/graviton_node_groups.tf
- aws/eks-managed-node-groups/node_groups.tf
fix in userdata
```release-note
NONE
```
> fix in userdata

- aws/eks-customer/route53.tf
Fix will fix thanos grpc record name
```release-note
None
```
> CLD-8806: Fix thanos grpc route53 record

- aws/eks-customer/github.tf
- aws/eks-customer/providers.tf
- aws/eks-customer/remove-utility.tf
- aws/eks-customer/scripts/utils.sh
- aws/eks-customer/utility.tf
- aws/eks-customer/variables.tf
Migrate checkout command to Github via Github App 
```release-note
```
> feat: Migrate script to Github App

- aws/eks-customer/remove-utility.tf
- aws/eks-customer/scripts/utils.sh
- aws/eks-customer/utility.tf
We need to generate proper Github token to clone repos with the JWT generated from the terraform provider 
```release-note
NONE
```
> fix: Generate Github token from JWT

- aws/eks-customer/github.tf
- aws/eks-customer/providers.tf
- aws/eks-customer/remove-utility.tf
- aws/eks-customer/scripts/deploy-utility.sh
- aws/eks-customer/scripts/remove-utility.sh
- aws/eks-customer/scripts/utils.sh
- aws/eks-customer/utility.tf
Proper GITHUB_TOKEN usage 
```release-note
```
> fix: Final fix for Github

- aws/server-auth/README.md
- aws/server-auth/cloud-server-auth.tf
Fix api gateway deployment warning
https://mattermost.atlassian.net/browse/CLD-8772
```release-note
NONE
```
> Fix api gateway deployment warning

- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/awat/variables.tf
- aws/customer-web-server/README.md
- aws/customer-web-server/variables.tf
- aws/customer-web-server/web-server.tf
- aws/grafana/README.md
- aws/grafana/rds.tf
- aws/grafana/variables.tf
- aws/provisioner/README.md
- aws/provisioner/provisioner-db.tf
- aws/provisioner/variables.tf
Change secrets store approach
https://mattermost.atlassian.net/browse/CLD-8856
```release-note
NONE
```
> Change secrets store approach

- aws/github-runner/iam.tf
- aws/github-runner/locals.tf
Add missing region on Github Access IAM Role
```release-note
NONE
```
> fix: Add missing region on Github IAM Role

- aws/cluster/README.md
- aws/cluster/calico.tf
- aws/cluster/eks_addon.tf
- aws/cluster/manifests/calico_installation.yaml
- aws/cluster/manifests/felix_config.yaml
- aws/cluster/providers.tf
- aws/cluster/variables.tf
- aws/github-runner/README.md
Add calico support to eks cluster module
https://mattermost.atlassian.net/browse/CLD-8882
```release-note
NONE
```
> Add calico support to eks cluster module

- aws/cluster/calico.tf
Trim fixes
https://mattermost.atlassian.net/browse/CLD-8882
```release-note
NONE
```
> Trim fixes

- aws/cluster/calico.tf
- aws/cluster/locals.tf
Use null resources because kubernetes manifests didn't work as expected
```release-note
NONE
```
> Use null resources because kubernetes manifests didn't work as expected

- aws/iam-custom-resources/packer.tf
- aws/iam-custom-resources/variables.tf
create IAM role for github workflow to assume it for packer
https://mattermost.atlassian.net/browse/CLD-8899
```release-note
Create IAM role for packer 
```
> create IAM role for github workflow to assume it for packer

- aws/cluster/README.md
- aws/cluster/calico.tf
Make scripts more resilient
```release-note
NONE
```
> Make scripts more resilient

- aws/cluster/calico.tf
- aws/iam-custom-resources/README.md
> more calico fixes

- aws/cluster/README.md
- aws/cluster/worker_asg.tf
- aws/eks-managed-node-groups/README.md
- aws/eks-managed-node-groups/graviton_node_groups.tf
fix to use different LT per managed group
```release-note
```
> fix to use different LT per managed group

- aws/cluster/README.md
- aws/cluster/worker_asg.tf
- aws/eks-managed-node-groups/graviton_node_groups.tf
fix bug in LT 2
```release-note
NONE
```
> fix bug in LT 2

- aws/cluster/README.md
- aws/cluster/variables.tf
- aws/cluster/worker_asg.tf
Add customization ability of calico pods in cluster module
https://mattermost.atlassian.net/browse/CLD-8843
```release-note
NONE
```
> Add customization ability of calico pods in cluster module

- aws/external-dns/README.md
- aws/external-dns/iam.tf
- aws/external-dns/providers.tf
- aws/external-dns/variables.tf
Add IRSA for external DNS
https://mattermost.atlassian.net/browse/CLD-8980
```release-note
NONE
```
> Add IRSA for external DNS

- .github/dependabot.yml
Add dependabot configuration for GitHub Actions/workflows updates
https://mattermost.atlassian.net/browse/CLD-9008
> Add dependabot configuration for GitHub Actions updates

- aws/eks-customer/README.md
- aws/eks-customer/irsa.tf
- aws/eks-customer/utility_policies.tf
Add external-dns policy to eks-customer module
https://mattermost.atlassian.net/browse/CLD-9022
```release-note
NONE
```
> Add external-dns policy to eks-customer module

- aws/eks-customer/README.md
- aws/eks-customer/irsa.tf
- aws/eks-customer/utility_policies.tf
fix: name of utility
```release-note
NONE
```
> fix: name of utility

- aws/eks-customer/utility_policies.tf
Add missing permissions to external secrets for eks-customer
https://mattermost.atlassian.net/browse/CLD-9049
```release-note
NONE
```
> Add missing permissions to external secrets for eks-customer

- .github/workflows/ci.yaml
- .tflint.hcl
- Makefile
update master to main and makefile improve functions
```release-note
update master to main and makefile improve functions
```
> update master to main and makefile improve functions

- aws/provisioner/locals.tf
Remove provisioner-prod user - fix failure in empty variable
https://mattermost.atlassian.net/browse/CLD-9121
```release-note
NONE
```
> Remove provisioner-prod user - fix failure in empty variable

- aws/cloud-lambda-storage/README.md
- aws/cloud-lambda-storage/iam.tf
- aws/cloud-lambda-storage/variables.tf
Fix principal in lambda-role
```release-note
NONE
```
> Fix principal in lambda-role

- aws/cloud-lambda-storage/README.md
- aws/cloud-lambda-storage/iam.tf
- aws/cloud-lambda-storage/variables.tf
- aws/iam-custom-resources/README.md
- aws/iam-custom-resources/github.tf
Add github OIDC. Modify lambda role to use github OIDC.
https://mattermost.atlassian.net/browse/CLD-9141
```release-note
NONE
```
> Add github OIDC. Modify lambda role to use github OIDC.

- aws/eks-customer/utility_policies.tf
allow access to wiz kubernetes secret
https://mattermost.atlassian.net/browse/CLD-9098
```release-note
allow access to wiz kubernetes secret
```
> allow access to wiz kubernetes secret

- aws/eks-customer/README.md
- aws/iam-custom-resources/README.md
- aws/iam-custom-resources/private.tf
add private repo role
https://mattermost.atlassian.net/browse/CLD-9195
```release-note
NONE
```
> add private repo role

- aws/eks-customer/utility_policies.tf
Update wiz integration to connector
```release-note
```
> Update wiz integration to connector

- aws/rds-customer-cluster/main.tf
- aws/rds-customer-cluster/variables.tf
add pgvector parameter for rds
https://mattermost.atlassian.net/browse/CLD-9202
```release-note
```
> add pgvector parameter for rds

- aws/external-secrets/iam.tf
add env name on policy secret for external secrets
https://mattermost.atlassian.net/browse/CLD-9021
```release-note
add env name on policy secret for external secrets
```
> add env name on policy secret for external secrets

- aws/awat/README.md
- aws/awat/awat_db.tf
- aws/awat/variables.tf
- aws/customer-web-server/README.md
- aws/customer-web-server/variables.tf
- aws/customer-web-server/web-server.tf
- aws/elrond/README.md
- aws/elrond/elrond-db.tf
- aws/elrond/variables.tf
- aws/grafana/README.md
- aws/grafana/rds.tf
- aws/grafana/variables.tf
- aws/provisioner/README.md
- aws/provisioner/provisioner-db.tf
- aws/provisioner/variables.tf
- aws/rds-customer-cluster/README.md
Add calico network SG rule support for DBs
https://mattermost.atlassian.net/browse/CLD-9262
```release-note
NONE
```
> Add calico network SG rule support for DBs

- aws/iam-custom-resources-release/README.md
- aws/iam-custom-resources-release/plugin-store.tf
- aws/iam-custom-resources-release/providers.tf
- aws/iam-custom-resources-release/variables.tf
Add IAM role and policy for plugin store for release prod
https://mattermost.atlassian.net/browse/CLD-9264
```release-note
Add IAM role and policy for plugin store for release prod
```
> Add IAM role and policy for plugin store for release prod

- aws/iam-custom-resources/README.md
- aws/iam-custom-resources/db_disaster_recovery.tf
- aws/iam-custom-resources/packer.tf
- aws/iam-custom-resources/variables.tf
Move DR pipelines to role instead of user
https://mattermost.atlassian.net/browse/CLD-9276
```release-note
NONE
```
> Move DR pipelines to role instead of user

- aws/iam-custom-resources/README.md
- aws/iam-custom-resources/pulumi.tf
- aws/iam-custom-resources/variables.tf
Create role for pulumi
https://mattermost.atlassian.net/browse/CLD-9263
```release-note
NONE
```
> Create role for pulumi

- aws/eks-customer/README.md
- aws/eks-customer/eks_addons.tf
- aws/eks-customer/eks_managed_node-group.tf
- aws/eks-customer/scripts/deploy-utility.sh
- aws/eks-customer/utility-utils.tf
- aws/eks-customer/utility.tf
- aws/eks-customer/variables.tf
This PR introduces a solution to dynamically create custom Kubernetes manifests based on templates. The solution ensures that the necessary directories are created automatically and that placeholders within template files are dynamically replaced with environment-specific values.
This also fixes the race condition waiting for argocd deploy.
- https://mattermost.atlassian.net/browse/CLD-9330
- https://mattermost.atlassian.net/browse/CLD-9134
```release-note
dynamically create custom Kubernetes manifests in eks-customer
```
> dynamically create custom manifests for k8s utilities

- aws/server-auth/README.md
- aws/server-auth/cloud-server-auth.tf
- aws/server-auth/variables.tf
Add api-key-required variable to server-auth tf module
https://mattermost.atlassian.net/browse/CLD-9532
```release-note
NONE
```
> add api-key-required
