mattermost/mattermost-cloud-monitoring

chart-values/fluentd-elasticsearch_values.yaml, terraform/aws/modules/cluster-post-installation/elasticsearch.tf, terraform/aws/modules/cluster-post-installation/fluentd.tf
Ticket -> https://mattermost.atlassian.net/browse/MM-16306 
- Adding fluentd deployment in central monitoring cluster. 
- Fixing namespaces for kibana and elasticsearch.
=> MM-16306 Adding fluentd deployment in central monitoring cluster.

Makefile, terraform/aws/environments/test/cluster/main.tf, terraform/aws/environments/test/cluster/variables.tf, terraform/aws/modules/cluster/aws_auth_configmap.tf, terraform/aws/modules/cluster/prometheus-registration-service.tf, terraform/aws/modules/cluster/variables.tf
Ticket -> https://mattermost.atlassian.net/browse/MM-16542 
- Automate Prometheus Microservice deployment.
-- With this code the microservice is deployed as part fo the Central Command Control cluster.
-- No additional configuration is needed.
-- Only the private private_hosted_zoneid variable is required for this additional deployment
- A Makefile is added that when the environment is specified, by running make all it will deploy the whole Central Command and Control cluster infrastructure in the specified environment.
=> MM 16542 -  Automate Lambda deployment for Prometheus DNS Registration service.

chart-values/prometheus-client_values.yaml, terraform/aws/modules/cluster-post-installation/elasticsearch.tf, terraform/aws/modules/cluster-post-installation/prometheus-client.tf
Ticket -> https://mattermost.atlassian.net/browse/MM-16549
- Add configuration of Prometheus client
- Prometheus client will be used to get the metrics of the central command and control cluster, which will be analysed by the central monitoring Prometheus application.
=> MM-16549 Adding prometheus client configuration for central command and control cluster

terraform/aws/modules/cluster/master.tf, terraform/aws/modules/cluster/master_sg.tf
Ticket -> https://mattermost.atlassian.net/browse/MM-16550
As discussed with @jwilander we will keep both private and public endpoint at the moment. The private is used for all traffic between master and nodes, as well as the prometheus registration lambda application. Public is used only for k8s api commands and only specific members have access.
- We cannot fully move to only private endpoint at the moment as VPN service is sitting in a different VPC and although there is transit gtw the resolution of the k8s endpoint (which is using private hosted zone in the background) is not possible without manually setting dns forwarding. 
- Different solutions will be examined closer to production move.
- The ingress rule in the terraform code is needed because of the private endpoint which …
=> Mm 16550 Adding private endpoint access for internal traffic

Makefile, terraform/aws/environments/dev/cluster-post-installation/main.tf, terraform/aws/environments/dev/cluster/main.tf, terraform/aws/environments/dev/cluster/variables.tf, terraform/aws/environments/dev/route53-registration/main.tf, terraform/aws/environments/dev/route53-registration/variables.tf, terraform/aws/environments/test/cluster/variables.tf, terraform/aws/environments/test/route53-registration/main.tf, terraform/aws/environments/test/route53-registration/variables.tf, terraform/aws/modules/route53-registration/providers.tf, terraform/aws/modules/route53-registration/route53.tf, terraform/aws/modules/route53-registration/variables.tf
Ticket -> https://mattermost.atlassian.net/browse/MM-16551
This PR adds:
- A new module to handle automatic Route53 registration of all central command and control cluster services. In more detail:
- Prometheus
- Prometheus client
- Grafana
- Kibana
- Elasticsearch
- Mattermost Provisioner
- Auth service
- Adapts the dev environment to follow the latest naming convention (central command and control cluster)
- Updates Makefile to deploy the whole infrastructure with a single command
=> MM-16551 Adding automatic Route53 registration for central command cluster services

prometheus-dns-registration-service/Gopkg.lock, prometheus-dns-registration-service/main.go
Previously the Lambda function was getting all Route53 records and was updating the Prometheus Targets in the Prometheus Configmap. 
With this PR a label is added to each of the Prometheus Targets, which specifies the clusterID. 
This way the clusterID can be filtered in the Grafana dashboards.
=> MM-19383 Updating Lambda to add clusterID label in each Prometheus target

terraform/aws/environments/staging/cluster/main.tf, terraform/aws/environments/test/cluster/main.tf, terraform/aws/modules/cluster/cloud-server-auth.tf, terraform/aws/modules/cluster/variables.tf
With this PR:
- Lambda AUTH is deployed as part of the C&C cluster including all needed components such as SGs, IAM Roles, CloudWatch triggers, etc.
- API Gateway operating as Lambda Auth proxy is deployed as part of the C&C cluster.
=> MM-18873 Adding automated deployment of API Gateway and Lambda Auth

prometheus-dns-registration-service/main.go
Adding the alerting structure.
I've update the configmap for prometheus however everytime that runs it lost the alerting settings. this might fix the issue.
@stylianosrigas can we deploy once is approved?
=> add alerting

terraform/aws/environments/prod/4-command-and-control/3-cluster-post-installation/main.tf, terraform/aws/environments/prod/4-command-and-control/3-cluster-post-installation/variables.tf, terraform/aws/environments/staging/4-command-and-control/3-cluster-post-installation/main.tf, terraform/aws/environments/staging/4-command-and-control/3-cluster-post-installation/variables.tf, terraform/aws/environments/test/4-command-and-control/3-cluster-post-installation/main.tf, terraform/aws/environments/test/4-command-and-control/3-cluster-post-installation/variables.tf, terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf, terraform/aws/modules/cluster-post-installation/variables.tf, terraform/aws/modules/subnet-and-networking/provisioner_db_subnet_group.tf, terraform/aws/modules/subnet-and-networking/security_groups.tf, terraform/aws/modules/subnet-and-networking/subnet.tf
This PR add the Terraform code for:
- Creation of IAM Policies
- Attachment of policies to existing provisioner user
- Creation of DB Subnet Groups in each provisioning VPC
- Creation of RDS Security Group in each provisioning VPC
- Ignoring of tags after their creation in public subnets to avoid overwriting of kops k8s tags
=> MM-20770 Adding policies for provisioner user

terraform/aws/modules/cluster-post-installation/provisioner.tf, terraform/aws/modules/route53-registration/route53.tf
Moving Provisioner to use Internal nginx and internal ELB
- Changes pushed in all environments
- Provisioner tested both via direct DNS and AUTH function.
=> MM-18599 Moving Provisioner to use Internal nginx and internal ELB

terraform/aws/modules/cluster-post-installation/ingress.tf, terraform/aws/modules/cluster/master.tf
- Make C&C API endpoint private
- Remove old non used public NGINX controller. All apps should be using internal.
=> MM-19103 Turning C&C API private and removing non used public NGINX

prometheus-dns-registration-service/main.go
if the prometheus yaml config have setup Alertmanager the config was reverted and remove the alertmanager config, this fixes the issue
=> Alerting is not an array, fixing

terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf
when running the cloud re provisioner notice it needs this additional permission
=> add route53 additional permission

terraform/aws/environments/prod/4-command-and-control/3-cluster-post-installation/main.tf, terraform/aws/environments/prod/4-command-and-control/3-cluster-post-installation/output.tf, terraform/aws/environments/staging/4-command-and-control/3-cluster-post-installation/main.tf, terraform/aws/environments/staging/4-command-and-control/3-cluster-post-installation/output.tf, terraform/aws/environments/test/4-command-and-control/3-cluster-post-installation/main.tf, terraform/aws/environments/test/4-command-and-control/3-cluster-post-installation/output.tf, terraform/aws/modules/cluster-post-installation/flux.tf, terraform/aws/modules/cluster-post-installation/namespaces.tf, terraform/aws/modules/cluster-post-installation/output.tf, terraform/aws/modules/cluster-post-installation/provisioner-db.tf, terraform/aws/modules/cluster-post-installation/provisioner.tf, terraform/aws/modules/cluster-post-installation/variables.tf
This PR covers:
- adding FLUX for provisioner updates
- adding ignore states for already deployed provisioner resources (updates to Provisioner resources should be done in the Gitlab repo)
- create output message to describe manual step needed after Flux deployment
=> MM-22260 Adding FLUX for provisioner update

terraform/aws/modules/gitlab/chart_values.yaml, terraform/aws/modules/gitlab/gitlab-route53.tf, terraform/aws/modules/gitlab/gitlab.tf
- add the missing registry dns 
already applied in the environment
=> gitlab: add registry route53 registration

terraform/aws/modules/bind-server/bind-server-network-attachment.tf, terraform/aws/modules/cluster/cloud-server-auth.tf, terraform/aws/modules/cluster/elb-cloudwatch-alarms.tf, terraform/aws/modules/cluster/grafana-aws-metrics.tf, terraform/aws/modules/cluster/prometheus-registration-service.tf, terraform/aws/modules/vpc-setup/vpc.tf
This PR
- Changes lambda function deployments to use remote S3 bucket instead of local zip files.
- Adds a lifecycle for a new tag we are using via the Provisioner
=> Move lambda functions to use S3 for code source instead of local files

terraform/aws/environments/prod/4-command-and-control/3-cluster-post-installation/main.tf, terraform/aws/environments/prod/4-command-and-control/3-cluster-post-installation/variables.tf, terraform/aws/environments/staging/4-command-and-control/3-cluster-post-installation/main.tf, terraform/aws/environments/staging/4-command-and-control/3-cluster-post-installation/variables.tf, terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf
- Adding KMS permissions on provisioner user
- Fix `cloud_vpn_cidr` variable that was missing
https://mattermost.atlassian.net/browse/MM-24215
=> add kms permissions on provisioner user

terraform/aws/modules/bind-server/bind-servers.tf, terraform/aws/modules/bind-server/variables.tf, terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf, terraform/aws/modules/cluster/master_sg.tf, terraform/aws/modules/cluster/variables.tf, terraform/aws/modules/cluster/worker_sg.tf, terraform/aws/modules/eks-cluster/master_sg.tf, terraform/aws/modules/eks-cluster/variables.tf, terraform/aws/modules/eks-cluster/worker_sg.tf, terraform/aws/modules/subnet-and-networking/security_groups.tf, terraform/aws/modules/subnet-and-networking/variables.tf
Add Teleport SSH access to all SGs
https://mattermost.atlassian.net/browse/MM-24511 
This PR:
- Adds the 3022 port in all SGs of the Terraform modules
- The CIDR is parameterised 
- It adds kms:TagResource permission to the Cloud Provisioner
=> [MM 24511] Updating SGs in all modules to allow 3022 port for Teleport access

terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf, terraform/aws/modules/cluster-post-installation/variables.tf
Updating provisioner users to handle list of users
This PR updates the Post Installation TF module and specifically the Provisioner user permissions to be able to handle a list of users. Now a list of user names can be passes and they will all get the provisioner permissions.
=> Updating provisioner users to handle list of users

terraform/aws/modules/cluster-post-installation/provisioner_user_permissions.tf
This PR grants permissions to the provisioner's IAM in order to allow tagging secrets created with the secrets manager service. 
https://mattermost.atlassian.net/browse/MM-23151
https://github.com/mattermost/mattermost-cloud/pull/209
Signed-off-by: Gabriel Linden Sagula <gsagula@gmail.com>
=> MM-23151: added permission for tagging secrets

terraform/aws/modules/security/vpc_flow_logs.tf
Enabling S3 default encryption in VPC flow logs
https://mattermost.atlassian.net/browse/MM-24886
=> enabling S3 default encryption in VPC flow logs

terraform/aws/modules/subnet-and-networking/provisioner_db_parameter_group.tf
With this PR:
- The default Max available connections to RDS Aurora Clusters is increased to 16000.
https://mattermost.atlassian.net/browse/MM-24771
=> [MM-24711] Enabling 16000 Max connections for RDS Aurora Clusters

lambda-functions/grafana-aws-metrics/Gopkg.lock, lambda-functions/grafana-aws-metrics/main.go, terraform/aws/modules/cluster-post-installation/grafana.tf, terraform/aws/modules/cluster-post-installation/grafana_dashboard_configmaps.tf, terraform/aws/modules/cluster/grafana-aws-metrics.tf, terraform/aws/modules/quota-alarms/main.tf, terraform/aws/modules/quota-alarms/variables.tf
With this PR:
- Additional account quota metrics are created for RDS, S3, Load Balancer, Auto Scaling and VPC services (Grafana Metrics Lambda)
- New Grafana dashboard is created to monitor quota utilization.
- New Cloudwatch Alerts are created with TF that integrate with Mattermost and Opsgenie when quota utilization reaches a specified value.
- Additional permissions are added in the Lambda role to support new metrics.
https://mattermost.atlassian.net/browse/MM-25291
=> [MM-25291] Additional account quota metrics, Cloudwatch alerts and Grafana dashboard.

terraform/aws/modules/security/variables.tf, terraform/aws/modules/security/vpc_flow_logs.tf
- Change location of VPC flow logs to be stored in Security account S3 buckets
- making conditional if we want flow logs or not
=> move vpc flow logs to security account s3 buckets

terraform/aws/modules/subnet-and-networking-3az/security_groups.tf, terraform/aws/modules/subnet-and-networking-3az/variables.tf, terraform/aws/modules/subnet-and-networking/security_groups.tf, terraform/aws/modules/subnet-and-networking/variables.tf
Adding SG rule to allow private subnets of C&C VPC to access the RDS Provisioning databases to create tables
=> Adding SG rule to allow private subnets of C&C VPC to access the RDS databases to create tables

terraform/aws/modules/cluster-post-installation/database-factory.tf
Reducing database factory replicas to 1 to avoid local terraform file inconsistency
=> Reducing database factory replicas to 1 to avoid local terraform file inconsistency

terraform/aws/modules/atlantis/nginx_internal_values.yaml, terraform/aws/modules/chartmuseum/chart_values.yaml, terraform/aws/modules/chartmuseum/chartmuseum-route53.tf, terraform/aws/modules/chartmuseum/chartmuseum.tf, terraform/aws/modules/chartmuseum/providers.tf, terraform/aws/modules/chartmuseum/variables.tf, terraform/aws/modules/cluster/variables.tf, terraform/aws/modules/eks-cluster/variables.tf, terraform/aws/modules/eks-cluster/worker_asg.tf
This PR:
- Adds the Chartmuseum module that deploys and configures Chartmuseum
- Adds a separate variable for the worker private subnets to solve the Gitlab issues in zone us-east-1d
https://mattermost.atlassian.net/browse/MM-25242
=> MM-25242 Pushing chartmuseum configuration and Gitlab cluster fixes

terraform/aws/modules/database-factory/database_factory_user_permissions.tf
Adding sns:ListTopics permission for Database Factory to be able to deploy SNS topic when deploying new RDS Cluster.
=> Adding sns:ListTopics permission for Database Factory to be able to deploy SNS topic when deploying new RDS Cluster

terraform/aws/modules/database-factory/database_factory_user_permissions.tf
Add cloudwatch:ListTagsForResource and cloudwatch:DeleteAlarms permissions to Database factory user.
=> Adding cloudwatch permissions to get tags and delete alarms for Database factory user

terraform/aws/modules/provisioner/provisioner_user_permissions.tf
Adding provisioner permission to attach and detach IAM policies to roles. 
This change to permissions is associated to https://github.com/mattermost/mattermost-cloud/pull/273
=> [MM-27278] Adding provisioner permission to attach and detach IAM policies to roles.

terraform/aws/modules/customer-web-server/variables.tf, terraform/aws/modules/customer-web-server/web-server.tf
With this PR the option to select when a R53 record will be created for customer portal.
The reason for that is that we want this record to be created in Test environment but not in Prod because it is not managed in the account.
=> Adding option to select when to deploy R53 record for customer portal

terraform/aws/modules/subnet-and-networking-3az/security_groups.tf, terraform/aws/modules/subnet-and-networking/security_groups.tf
This PR:
- Deploys new DB security group for PostgreSQL support
- Adds DB security group rules to allow PostgreSQL access by the provisioner ,the provisioning cluster and VPN users in Dev environment.
https://mattermost.atlassian.net/browse/MM-27360
=> MM-27360 Adding security group for PostgreSQL and relevant DB subnet rules

terraform/aws/modules/cluster/aws_auth_configmap.tf, terraform/aws/modules/cluster/variables.tf, terraform/aws/modules/cluster/worker_iam.tf, terraform/aws/modules/eks-cluster/variables.tf, terraform/aws/modules/eks-cluster/worker_iam.tf, terraform/aws/modules/teleport/providers.tf, terraform/aws/modules/teleport/teleport.tf
With this PR:
- New cnc node policy is created for Teleport required permissions
- Teleport module is updated to include new set strings for external storage setup
- Local variables are created in auth configmap to support Mattewick access in Test environment
https://mattermost.atlassian.net/browse/MM-27333
=> [MM 27333] Enable Teleport external storage in CnC and Gitlab clusters.

terraform/aws/modules/subnet-and-networking-3az/provisioner_db_subnet_group.tf, terraform/aws/modules/subnet-and-networking/provisioner_db_subnet_group.tf
With this PR support for DB subnet groups deployment used by PostgreSQL DB clusters is added.
https://mattermost.atlassian.net/browse/MM-27475
=> [MM-27475] Adding DB subnet groups for PostgreSQL

terraform/aws/modules/provisioner-users/locals.tf, terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf, terraform/aws/modules/provisioner-users/provisioner_users.tf, terraform/aws/modules/provisioner-users/variables.tf, terraform/aws/modules/provisioner/variables.tf
Moving provisioner permissions in a separate module to enable deployment of dev users in a single place
https://mattermost.atlassian.net/browse/MM-28091
=> [MM-28091] Moving provisioner permissions in a separate module to enable deployment of dev users in a single place

terraform/aws/modules/provisioner/provisioner.tf, terraform/aws/modules/provisioner/variables.tf
You can see the log here:
The CLI [doesn't support the private-dns option](https://github.com/mattermost/mattermost-cloud/commit/485566eda810abdc5f2a3d6345e9d00c1cd95ffe#diff-bf5173f7bde99c71fd86043720c9c5d3bb52a48cca5c8d22da09e358b7d43c53) anymore so when deploy the cloud pods they're in the CrashLoopBackoff state until you remove this option.
```
$ k logs mattermost-cloud-installations-76c89d4854-m9g9t --previous
Usage:
cloud server [flags]
Flags:
--allow-list-cidr-range strings                The list of CIDRs to allow communication with the private ingress. (default [0.0.0.0/0])
--cluster-installation-supervisor              Whether this server will run a cluster installation supervisor or not. (default true)
--cluster-resource-threshold int               The percent threshold where …
```
=> [MM-29019] Private DNS for mattermost-cloud is removed

terraform/aws/modules/atlantis/atlantis.tf, terraform/aws/modules/atlantis/nginx-internal.tf, terraform/aws/modules/atlantis/providers.tf, terraform/aws/modules/chartmuseum/chartmuseum.tf, terraform/aws/modules/chartmuseum/providers.tf, terraform/aws/modules/cluster-post-installation/blackbox.tf, terraform/aws/modules/cluster-post-installation/es-curator.tf, terraform/aws/modules/cluster-post-installation/fluent-bit.tf, terraform/aws/modules/cluster-post-installation/flux.tf, terraform/aws/modules/cluster-post-installation/grafana.tf, terraform/aws/modules/cluster-post-installation/grafana_dashboard_configmaps.tf, terraform/aws/modules/cluster-post-installation/prometheus_operator.tf, terraform/aws/modules/cluster-post-installation/providers.tf, terraform/aws/modules/cluster-post-installation/thanos.tf, terraform/aws/modules/customer-web-server/flux.tf, terraform/aws/modules/database-factory-scaling/cloud_db_factory_vertical_scaling.tf, terraform/aws/modules/eks-cluster/kubeconfig.tf, terraform/aws/modules/flux/flux.tf, terraform/aws/modules/gitlab/gitlab.tf, terraform/aws/modules/gitlab/gitlab_cert.tf, terraform/aws/modules/gitlab/providers.tf, terraform/aws/modules/gitlab/s3.tf, terraform/aws/modules/provisioner/locals.tf, terraform/aws/modules/public-ingress/nginx-public.tf, terraform/aws/modules/teleport/providers.tf, terraform/aws/modules/teleport/teleport.tf
- Migrate Helm2 releases to Helm3
- Module cleanup to follow Terraform 0.13 rules.
https://mattermost.atlassian.net/browse/MM-25815
=> MM-25815 Migrate Helm2 releases to Helm3, module cleanup to follow Terraform 0.13 rules.

terraform/aws/modules/atlantis/atlantis.tf, terraform/aws/modules/atlantis/providers.tf, terraform/aws/modules/atlantis/variables.tf
Remove deprecated declarations
Try to fix:
```
in provider "helm":
29:     load_config_file       = false
An argument named "load_config_file" is not expected here.
```
on terraform plan
=> MM-24482: Helm fixes

terraform/aws/modules/atlantis/providers.tf, terraform/aws/modules/chartmuseum/providers.tf, terraform/aws/modules/flux/providers.tf, terraform/aws/modules/gitlab/providers.tf, terraform/aws/modules/public-ingress/providers.tf, terraform/aws/modules/teleport/providers.tf
Following cluster_post_installation setup.
Remove failing load_config_value parameter.
Add back helm provider to atlantis
=> Update helm providers

terraform/aws/modules/cluster-post-installation/flux.tf, terraform/aws/modules/cluster-post-installation/grafana.tf, terraform/aws/modules/customer-web-server/flux.tf, terraform/aws/modules/teleport/teleport.tf
Substitute `set_string` with `set`. 
Ref.
```
set_string deprecation
set_string it's a very ad-hoc argument, implemented in a way that simply doesn't scale. set_sensitive was missing the functionality of string so following the pattern we should introduce set_sensitive_string what it's simply horrible.
Instead of doing this set_string has been deprecated in favor of set with the option type equal to string, behaves exactly as set_string. Additionally now set_sensitive also has the functionally as string.
```
Substitute `set_string` with `set`. 
`NONE`
=> Fix deprecations

terraform/aws/modules/cluster/worker_asg.tf
Noticed some OOM on kubelet operations and Nodes become not ready on
test environment.
The idea for these flags come from a useful resource regarding running
EKS on production. ref. https://kubedex.com/90-days-of-aws-eks-in-production/
Reserving Resources For The System and Kubelet
`NONE`
=> Reserving Resources For The System and Kubelet

terraform/aws/modules/customer-web-server/variables.tf, terraform/aws/modules/customer-web-server/web-server.tf
This PR introduces multiple changes to fix the CWS deployment with Terraform:
- The old payment variables were deprecated and deleted in [this](https://github.com/mattermost/customer-web-server/commit/cbfb12422ebeeb0d66ac15581f8f90514228dbf9#diff-5dbee3ab19f33590cb8f06c1c3a5274e2d59ea4e530503d54802cf2d212f5cfc) commit.
Right now the variable to be used is CWS_STRIPE_KEY
- Added missing variables to create the secret that would be used by CWS in form of env. variables
- Exposed port 8077 as the internal API
=> Fixed CWS terraform scripts

terraform/aws/modules/cluster-logging/es-curator.tf, terraform/aws/modules/cluster-logging/fluent-bit.tf, terraform/aws/modules/cluster-logging/namespaces.tf, terraform/aws/modules/cluster-logging/variables.tf
This is a new module to only deploy the cluster logging part with fluentbit and es-curator.
Is not using flux and probably we want to have flux as optional but I just want to have this PR here as a food for thought
=> Cluster logging module

lambda-functions/deckhand/main.go, terraform/aws/modules/cleanup-unused-images/lambdas.tf
```
Lambda was unable to configure your environment variables because the environment variables you have provided contains reserved keys that are currently not supported for modification. Reserved keys used in this request: AWS_REGION
```
Renaming to REGION.
=> Bug-fix: Cannot use key AWS_REGION in ENV_VARIABLE

terraform/aws/modules/cleanup-unused-images/cloudwatch.tf, terraform/aws/modules/cleanup-unused-images/iam.tf
Add back required permissions for lambda creation
Add event target needed for lambda to be cron.
Add back required permissions for lambda creation.
=> Add event target needed for lambda to be cron

terraform/aws/modules/customer-web-server/variables.tf, terraform/aws/modules/customer-web-server/web-server.tf, terraform/aws/modules/provisioner/route53.tf
In order to make it possible to CIDR filtering for CWS, we need to expose the public API through the internal endpoint so we can filter based on our internal cluster API.
The current internal endpoint/ingress is renamed as api.internal and that would lead to the CWS internal API
https://mattermost.atlassian.net/browse/MM-29654
=> [MM-29654] Split internal ingress for CWS

terraform/aws/modules/customer-web-server/web-server.tf
Signed-off-by: Mario de Frutos <mario@defrutos.org>
Fixed bug for api.internal CNAME in CWS module
=> Fix bug with CNAME for internal api CWS

terraform/aws/modules/database-factory/database_factory_user_permissions.tf
Database factory was failing in test as we were lacking the permission
for modifying the DB cluster.
https://mattermost.atlassian.net/browse/MM-34230
=> Fix permissions of database factory user to be able to modify the cluster

.circleci/config.yml, terraform/aws/modules/cleanup-unused-images/lambdas.tf, terraform/aws/modules/cleanup-unused-images/variables.tf
Make s3 bucket variable for deckhand lambda as we need to deploy it in multiple buckets.
Add new pipeline to support multiregion lambda deployments.
https://mattermost.atlassian.net/browse/MM-34662
=> Add new pipeline to support multiregion lambda deployments.

terraform/aws/modules/customer-web-server/variables.tf, terraform/aws/modules/customer-web-server/web-server.tf, terraform/aws/modules/provisioner/provisioner-db.tf, terraform/aws/modules/provisioner/variables.tf
Read replica doesn't need subnet group when it is in the same
region and there is no need for backups for replicas. Set
availability zone to be assigned and not use the same as master
https://mattermost.atlassian.net/browse/MM-34759
=> Fix read replica remove the subnet group

terraform/aws/modules/vpc-setup/cluster_nodes_iam.tf
Add permission needed by k8s-spot-termination-handler. 
k8s-spot-termination-handler pods need to be able to describe ASG instances. 
https://mattermost.atlassian.net/browse/MM-34603
=> Add permission needed by k8s-spot-termination-handler

terraform/aws/modules/elasticsearch/locals.tf, terraform/aws/modules/elasticsearch/monitoring.tf, terraform/aws/modules/elasticsearch/variables.tf
Alarms for:
- FreeStorageSpace
- ClusterIndexWritesBlocked
- ClusterStatus.yellow/red
- Min Nodes
- CPUUtilization
- JVMMemoryPressure
- MasterCPUUtilization
- MasterJVMMemoryPressure
https://mattermost.atlassian.net/browse/MM-34089
=> Add cloudwatch alarms for elasticsearch

terraform/aws/modules/cluster-logging/fluent-bit.tf, terraform/aws/modules/cluster-post-installation/fluent-bit.tf
We are bumping the version of fluent-bit and we need to source the new
official helm chart.
https://mattermost.atlassian.net/browse/MM=35208
=> Change fluentbit helm to the official chart

terraform/aws/modules/atlantis/rbac.tf
We need to give access to watch and list other k8s resources which are needed so
we can runn terraform operations with atlantis. The current issue is that it's missing
permissions to describe specific resources so the terraform operations fail.
https://mattermost.atlassian.net/browse/MM-35192
=> Fix service account of atlantis to have the right permissions

terraform/aws/modules/cluster/providers.tf
**Reasoning:**
Some cloud providers have short-lived authentication tokens that can expire relatively quickly. To ensure the Kubernetes provider is receiving valid credentials, an exec-based plugin can be used to fetch a new token before initializing the provider. For example, on EKS.
**Reference:**
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs
https://mattermost.atlassian.net/browse/MM-35549
=> Fix: Get eks token with exec

terraform/aws/modules/cluster/providers.tf, terraform/aws/modules/cluster/variables.tf
If this commit applied aws profile could pass as param on cluster module when it get's token. This way can be ensured that it will use the profile which had the proper permissions and not one inherited from EC2 instance role.
Issue: MM-35549
Pass AWS_PROFILE as param
https://mattermost.atlassian.net/browse/MM-35549
=> Pass AWS_PROFILE as param

terraform/aws/modules/elasticsearch/outputs.tf
We need to use the endpoint elasticsearch is created in AWS so we can pass this
as reference to the elasticsearch provider.
https://mattermost.atlassian.net/browse/MM-35823
=> Expose output for the endpoint of the elasticsearch

terraform/aws/modules/cluster/providers.tf
If this commit applied accompanied with upgrade of kubernetes provider to 2.2.0 and aws provider to 3.39.0 will fix the cluster authentication issues.
https://mattermost.atlassian.net/browse/MM-35830
=> Fix config cluster auth failure

terraform/aws/modules/cluster/worker_iam.tf
If this commit applied workers ant their pods will be able to do AWS cost Explorer API calls
Issue: MM-36029
Add cost explorer permissions to workers
https://mattermost.atlassian.net/browse/MM-36029
=> Add cost explorer permissions to workers

terraform/aws/modules/bind-server/bind-servers.tf, terraform/aws/modules/bind-server/variables.tf
If this commit applied bind server could have different volume size based on the needs of each use-case.
Issue: MM-36079
Add volume size & type as variables to bind servers
https://mattermost.atlassian.net/browse/MM-36079
=> Add volume size & type as variables to bind servers

terraform/aws/modules/bind-server/bind-servers.tf, terraform/aws/modules/bind-server/locals.tf, terraform/aws/modules/bind-server/monitoring.tf, terraform/aws/modules/bind-server/variables.tf
If this commit applied bind servers would have proper permissions to be able to monitor their volumes.
Issue: MM-36080
If this commit applied bind servers would have proper permissions to be able to monitor their volumes.
https://mattermost.atlassian.net/browse/MM-36080
=> Add required roles for EBS monitoring on Bind Servers

terraform/aws/modules/gitlab/gitlab-route53.tf
Adapt Gitlab Route53 to work with new k8s provider
=> Adapt Gitlab Route53 to work with new k8s provider

terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
Add permission for provisioner to allow TagRole for nodes.
https://mattermost.atlassian.net/browse/MM-37050
=> MM-37050 Adding tag role permission for provisioner

.circleci/config.yml, terraform/aws/modules/provisioner-users/provisioner_user_permissions.tf
If this commit applied nodes will have the permissions that new version of Kops 1.21 needs to create a new cluster.
We hit the limit of policies that can be attached so also repurposed mattermost-provisioner-ec2-policy to include any new categories needed that we don't have a specific policy for them already attached.
https://mattermost.atlassian.net/browse/MM-37151
=> Add AWS permissions for Kops 1.21

terraform/aws/modules/route53-registration/route53.tf
- Enable R53 record for chaos mesh endpoint
https://mattermost.atlassian.net/browse/MM-36824
=> [MM-36824] Enable R53 record for chaos mesh endpoint

terraform/aws/modules/bind-server/monitoring.tf
The rule is typed incorrectly so we update to the correct value `LessThanOrEqualToThreshold`
Ticket: https://mattermost.atlassian.net/browse/M-37023
=> [bind-server] Fix typo for monitoring rule in cloudwatch

terraform/aws/modules/awat/awat_db.tf, terraform/aws/modules/awat/variables.tf
Seems that AWS forces a major version upgrade which fails because of hardcoded false value.
Issue: MM-38045
Seems that AWS forces a major version upgrade which fails because of hardcoded false value.
https://mattermost.atlassian.net/browse/MM-38045
=> Add variable for major_version_upgrade

terraform/aws/modules/route53-registration/providers.tf, terraform/aws/modules/route53-registration/route53.tf
Issue: MM-38444
Fix endpoint syntax to be in sync with 2.4.1 kubernetes provider
https://mattermost.atlassian.net/browse/MM-38444
=> Fix endpoint syntax to be in sync with 2.4.1 kubernetes provider

terraform/aws/modules/eks-cluster/worker_iam.tf
- Fix wrong naming for eks kube2iam policy
=> Fix wrong naming for eks kube2iam policy

terraform/aws/modules/chaos-engine/README.md, terraform/aws/modules/chaos-engine/locals.tf, terraform/aws/modules/chaos-engine/main.tf, terraform/aws/modules/chaos-engine/outputs.tf, terraform/aws/modules/chaos-engine/providers.tf, terraform/aws/modules/chaos-engine/variables.tf, terraform/aws/modules/customer-web-server/web-server.tf
The chaos engine module refers the infra needed for the Mattermost Applications
[chaos engine](https://github.com/mattermost/mattermost-app-chaosengine).
Ticket: https://mattermost.atlassian.net/browse/MM-38884
=> Add module for chaos engine

.circleci/config.yml, lambda-functions/logs-to-opensearch/Makefile, lambda-functions/logs-to-opensearch/index.js, terraform/aws/modules/cleanup-unused-images/lambdas.tf, terraform/aws/modules/logs-to-opensearch/README.md, terraform/aws/modules/logs-to-opensearch/cloudwatch.tf, terraform/aws/modules/logs-to-opensearch/iam.tf, terraform/aws/modules/logs-to-opensearch/lambdas.tf, terraform/aws/modules/logs-to-opensearch/locals.tf, terraform/aws/modules/logs-to-opensearch/variables.tf
Issue: MM-39482
Add lambda to ship Cloudwatch logs to Opensearch.
The first logs we need to expose are them from Aurora Postgres Clusters
https://mattermost.atlassian.net/browse/MM-39842
=> Add lambda to ship Cloudwatch logs to Opensearch

terraform/aws/modules/velero/locals.tf, terraform/aws/modules/velero/variables.tf, terraform/aws/modules/velero/velero_iam.tf, terraform/aws/modules/velero/velero_s3.tf
Terraform Module to setup Velero dependencies like Bucket to store backup/restore data , Plus IAM role for velero deployment with Kube2IAM.
https://mattermost.atlassian.net/browse/MM-39991
=> MM-39992 added velero module to create Bucket & related IAM role

terraform/aws/modules/database-factory/database_factory_user_permissions.tf
Issue: MM-40164
Add permissions for lambda and cloudwatch logs to database factory
https://mattermost.atlassian.net/browse/MM-40164
=> Add permissions for lambda and cloudwatch logs to database factory

terraform/aws/modules/database-factory/database_factory_user_permissions.tf, terraform/aws/modules/database-factory/variables.tf
After migrating to Kube2IAM role base access, we can remove not required user & relative IAM policy attachment.
https://mattermost.atlassian.net/browse/MM-40190
=> MM-40190-remove-unused-iam-user-and-permissions

aws/vpc-setup/cluster_nodes_iam.tf
This is a temporary solution we really need to invest time to have one single point of
infrastructure as a code for cluster creation. Right now is not clear where is this going
to be attached but in practice is attached in Provisioner codebase. Check this file and
specifically this line [here](https://github.com/mattermost/mattermost-cloud/blob/master/internal/provisioner/kops_provisioner_cluster.go#L208). There are extra lines like this.
https://mattermost.atlassian.net/browse/CLD-998
```release-note
Update VPC setup with extra node policy
```
=> [vpc-setup] Add an extra policy for velero permissions

aws/cluster/variables.tf, aws/cluster/worker_asg.tf, aws/eks-managed-node-groups/variables.tf
Set ebs_optimized flag to null for cluster defaults
Addresses https://mattermost.atlassian.net/browse/CLD-2311
```release-note
- Set ebs_optimized flag to null for cluster defaults
```
=> Set ebs_optimized flag to null for cluster defaults

aws/database-factory/database_factory_user_permissions.tf
Adding new permissions for new database-factory feature of restoring from snapshot 
Addresses CLD-3865
```release-note
- Adding new permissions for new database-factory feature
```
=> Adding new permissions for new database-factory feature

aws/database-factory/database_factory_user_permissions.tf
Adding RestoreDBClusterFromSnapshot to cluster-snapshots from anywhere
Fixes CLD-3865
```release-note
- Adding RestoreDBClusterFromSnapshot to cluster-snapshots from anywhere
```
=> Adding RestoreDBClusterFromSnapshot to cluster-snapshots from anywhere

aws/provisioner-users/provisioner_user_permissions.tf
Issue: CLD-4038
Add missing permissions to provisioner users
https://mattermost.atlassian.net/browse/CLD-4038
```release-note
NONE
```
=> Add missing permissions to provisioner users

aws/grafana-aws-metrics/grafana-aws-metrics.tf, aws/grafana-aws-metrics/variables.tf, aws/provisioner/provisioner-db.tf, aws/provisioner/variables.tf
- Allow cross account assume role access from centralised monitoring
```release-note
- Allow cross account assume role access from centralised monitoring
```
=> [CLD-4097] Allow cross account assume role access from centralised monitoring

aws/provisioner-users/provisioner_user_permissions.tf
Issue: CLD-4038
Fix bucket permissions for kops 1.22 upgrade
https://mattermost.atlassian.net/browse/CLD-4038
```release-note
NONE
```
=> Fix bucket permissions for kops 1.22 upgrade

aws/elasticsearch/variables.tf
Fix variable types for elasticsearch values
https://mattermost.atlassian.net/browse/CLD-4223
```release-note
- Fix variable types for elasticsearch values
```
=> Fix elasticsearch values

aws/elasticsearch/elasticsearch.tf, aws/elasticsearch/variables.tf
Adding more granular access to elasticsearch clusters
https://mattermost.atlassian.net/browse/CLD-4223
```release-note
Adding more granular access to elasticsearch clusters
```
=> Adding more granular access to elasticsearch clusters

aws/community-infra/rds_route53.tf, aws/community-infra/variables.tf
Add generic DNS names for community RDS
https://mattermost.atlassian.net/browse/CLD-4271
```release-note
- Add generic DNS names for community RDS
```
=> Add generic DNS names for community RDS

aws/customer-web-server/web-server.tf
Fix wrong subnet usage in cws module
```release-note
NONE
```
=> Fix wrong subnet usage in cws module

aws/provisioner-users/provisioner_user_permissions.tf
Add new permission to provisioner user for e2e test, found that these missing permissions didn't allow cluster deletion on kops 1.22+
Fixes https://mattermost.atlassian.net/browse/CLD-4632
```release-note
- Add new permission to provisioner user for e2e test
```
=> Add new permission to provisioner user for e2e test

aws/lambda-promtail/cloudwatch.tf, aws/lambda-promtail/iam.tf, aws/lambda-promtail/lambdas.tf, aws/lambda-promtail/variables.tf
Issue:
Make promtail module capable to create second instance in the same account
```release-note
NONE
```
=> Make promtail module capable to create second instance in the same account

aws/provisioner-users/provisioner_user_permissions.tf
Issue: CLD-4634
Signed-off-by: Andre Leite [andrleite@gmail.com](mailto:andrleite@gmail.com)
It'll add depends on user creation to policy attachment to avoid errors like this:
```
Error: Error attaching policy arn:aws:iam::<redacted>:policy/mattermost-provisioner-rds-policy to IAM User andre.test-provisioner: NoSuchEntity: The user with name andre.test-provisioner cannot be found.
status code: 404, request id: <redacted>
Error: Error attaching policy arn:aws:iam::<redacted>:policy/mattermost-provisioner-secretsmanager-policy to IAM User andre.test-provisioner: NoSuchEntity: The user with name andre.test-provisioner cannot be found.
status code: 404, request id: <redacted>
Error: Error attaching policy arn:aws:iam::<redacted>:policy/mattermost-provisioner-ec2-policy to IAM User …
```
=> Adding depends on to user policy attachment

aws/database-factory/README.md, aws/database-factory/database_factory_user_permissions.tf
Issue: CLD-4490
Signed-off-by: Andre Leite [andrleite@gmail.com](mailto:andrleite@gmail.com)
Add devops-guru aws permission to dbfactory
Fixes https://mattermost.atlassian.net/browse/CLD-4490
```release-note
NONE
```
=> [CLD-4490]: Add devops-guru aws permission to dbfactory

aws/cluster/argocd_iam.tf, aws/cluster/aws_auth_configmap.tf
This role is needed for ArgoCD to connect to EKS clusters in other accounts. It has been tested manually as part of CLD-4881 and is now being defined in IaC. This will apply to all CnC clusters.
https://mattermost.atlassian.net/browse/CLD-4882
```release-note
- Add ArgoCD-Deployer Role for ArgoCD access to EKS clusters.
```
=> Add new argocd deployer role for ArgoCD cluster access

aws/cluster/argocd_iam.tf
Fix variable reference in ArgoCD IAM Role for clusters
https://mattermost.atlassian.net/browse/CLD-4882
```release-note
- Fix variable reference in ArgoCD IAM Role for clusters
```
=> Add quotes around argocd_account_role

aws/cluster/README.md, aws/cluster/aws_auth_configmap.tf, aws/cluster/variables.tf
Add read only role to aws auth configmap and create k8s read-only cluster role
Fixeshttps://mattermost.atlassian.net/browse/CLD-4578
```release-note
- Add read only role to aws auth configmap
- Create k8s read-only cluster role
```
=> [CLD-4578]: Add read only role to aws auth configmap

aws/cluster/README.md, aws/eks-cluster/README.md, aws/eks-cluster/variables.tf, aws/eks-cluster/worker_asg.tf, aws/eks-managed-node-groups/README.md
Issue: CLD-4911
Add support for zone Aware spot instances to eks-cluster module
https://mattermost.atlassian.net/browse/CLD-4911
```release-note
NONE
```
=> Add support for zone Aware spot instances to eks-cluster module

aws/calls-offloader/main.tf, aws/calls-offloader/networking.tf
Remove timestamps to prevent terraform changes for calls offloader
```release-note
- Remove timestamps to prevent terraform changes for calls offloader
```
=> Remove timestamps to prevent terraform changes for calls offloader

aws/calls-offloader/main.tf
Add proper network interface to launch template calls offloader
https://mattermost.atlassian.net/browse/CLD-5391
```release-note
- Add proper network interface to launch template calls offloader
```
=> Add proper network interface to launch template calls offloader

aws/eks-managed-node-groups/spot_node_groups.tf
Fix ternary assignment in eks-managed-nodes
https://mattermost.atlassian.net/browse/CLD-5357
```release-note
- Fix ternary assignment in eks-managed-nodes
```
=> Fix ternary assignment in eks-managed-nodes

aws/iam-custom-resources/db_disaster_recovery.tf, aws/iam-custom-resources/local.tf
Added secret manager read-only permission for db_disaster_recovery user
https://mattermost.atlassian.net/browse/CLD-5536
```release-note
Added secret manager read-only permission for db_disaster_recovery user
```
=> Added secret manager permission for DR Recovery policy

aws/cluster/README.md, aws/cluster/master.tf, aws/cluster/providers.tf, aws/cluster/worker_asg.tf, aws/eks-managed-node-groups/README.md, aws/eks-managed-node-groups/providers.tf
- Remove tags from the EKS cluster due to a possible bug https://github.com/hashicorp/terraform-provider-aws/issues/18852
- Update k8s provider from 2.0 to 2.20
```release-note
Update k8s provider from 2.0 to 2.20
```
=> Fix/5438 - Remove tags from eks cluster and update k8s provider

aws/rds-cloudwatch-alarms/README.md, aws/rds-cloudwatch-alarms/cloudwatch.tf, aws/rds-cloudwatch-alarms/providers.tf, aws/rds-cloudwatch-alarms/variables.tf
- Created cloudwatch alarm dedicated module for terragrunt use
@stafot when merged we can incorporate it in the aurora module for consistency. WDYT ? It's the same code. 
https://mattermost.atlassian.net/browse/CLD-5351
```release-note
```
=> feat: Create RDS Cloudwatch alarms dedicated module

aws/provisioner-users/provisioner_user_permissions.tf
Issue: CLD-4746
Add autoscaling permissions for kops 1.24
https://mattermost.atlassian.net/browse/CLD-4746
```release-note
NONE
```
=> Add autoscaling permissions for kops 1.24

aws/provisioner-users/provisioner_user_permissions.tf
Adding IAM get role and instance profile permissions to provisioner for kops 1.25
https://mattermost.atlassian.net/browse/CLD-6212
```release-note
Adding IAM get permissions to provisioner user
```
=> Adding IAM get role and instance profile permissions to provisioner for kops 1.25

aws/vpc-setup/installation_iam_users.tf
Add permissions needed to IAM user when custom KMS encryption exists
https://mattermost.atlassian.net/browse/CLD-6288
```release-note
NONE
```
=> Add permissions needed to IAM user when custom KMS encryption exists

aws/rds-customer-cluster/main.tf
- Add database_name parameter to block global cluster recreations
```release-note
- Add database_name parameter to block global cluster recreations
```
=> Add database_name parameter to block global cluster recreations

aws/cloudwatch-alarms/README.md, aws/cloudwatch-alarms/cloudwatch-alarms.tf, aws/cloudwatch-alarms/example/main.tf, aws/cloudwatch-alarms/example/variables.tf, aws/cloudwatch-alarms/variables.tf, aws/cloudwatch-event-alerts/README.md, aws/cloudwatch-event-alerts/cloudwatch-event-alerts.tf, aws/cloudwatch-event-alerts/variables.tf, aws/generic-webhook-notification/README.md, aws/generic-webhook-notification/lambdas.tf, aws/generic-webhook-notification/variables.tf, aws/rds-cluster-events/README.md, aws/rds-cluster-events/rds-cluster.events.tf, aws/rds-cluster-events/variables.tf
- Update lambda deployments to use Pagerduty instead of Opsgenie
```release-note
- Update lambda deployments to use Pagerduty instead of Opsgenie
```
=> [CLD-7311] Update lambda deployments to use Pagerduty instead of Opsgenie

aws/vpc-setup/vpc.tf
Summary
This PR will add a new tag for VPCs to identify which kind of cluster is using it. the default value is kops. More details in the ticket.
Ticket Link
Fixes https://mattermost.atlassian.net/browse/CLD-8072
```release-note
None
```
=> [CLD-8072]adding new tag for vpcs

aws/transit-gateway-attachment/main.tf, aws/transit-gateway-attachment/variables.tf
add security_group_referencing_support for aws_ec2_transit_gateway_vpc_attachment and setting default to disable
https://mattermost.atlassian.net/browse/CLD-8152
```release-note
add security_group_referencing_support for aws_ec2_transit_gateway_vpc_attachment and setting default to disable
```
=> add security_group_referencing_support for aws_ec2_transit_gateway_vpc_attachment and setting default to disable

aws/cluster-autoscaler/README.md, aws/cluster-autoscaler/variables.tf, aws/transit-gateway-attachment/README.md
Fix bug in cluster-autoscaler module
https://mattermost.atlassian.net/browse/CLD-8401
```release-note
ΝΟΝΕ
```
=> Fix bug in cluster-autoscaler module

Makefile, aws/transit-gateway-attachment/main.tf, aws/transit-gateway-attachment/variables.tf, aws/transit-gateway/README.md, aws/transit-gateway/providers.tf, aws/transit-gateway/tgw_attachment.tf, aws/transit-gateway/variables.tf
add security_group_referencing_support in tgw and add support for macos for make setup
https://mattermost.atlassian.net/browse/CLD-8152
```release-note
add security_group_referencing_support in tgw and add support for macos for make setup
```
=> add security_group_referencing_support in tgw and add support for macos for make setup

aws/eks-customer/README.md, aws/eks-customer/utility-utils.tf
Fix Bifrost service Account annotation
```release-note
None
```
=> Fix bifrost service account annotation

.github/workflows/ci.yaml
This is a temporary fix due to missing terraform command in ubuntu-latest in GitHub actions
Fixes https://mattermost.atlassian.net/browse/CLD-8459
```release-note
None
```
=> CLD-8459: Temporary change Ci image

aws/s3-data/README.md, aws/s3-data/main.tf, aws/s3-data/variables.tf
add ability to enable versioning for s3 data bucket
https://mattermost.atlassian.net/browse/CLD-8563
```release-note
add ability to enable versioning for s3 data bucket
```
=> add ability to enable versioning for s3 data bucket

aws/s3-data/README.md, aws/s3-data/main.tf
add atlantis data eng user_id into S3 bucket policy as Atlantis was failing to manage the bucket
https://mattermost.atlassian.net/browse/CLD-8568
```release-note
add atlantis data eng user_id into S3 bucket policy
```
=> add atlantis data eng user_id into S3 bucket policy

aws/eks-customer/README.md, aws/eks-customer/irsa.tf, aws/eks-customer/utility_policies.tf
Add cluster-autoscaler
https://mattermost.atlassian.net/browse/CLD-8753
```release-note
None
```
=> CLD-8753: Add cluster-autoscaler

aws/eks-customer/remove-utility.tf
Resolving this issue: 
```
Error: Invalid reference from destroy provisioner
on .terraform/modules/eks/aws/eks-customer/remove-utility.tf line 16, in resource "null_resource" "remove-utilities":
16:     environment = {
17:       GIT_REPO_PATH     = self.triggers.gitops_repo_path
18:       GIT_REPO_URL      = self.triggers.gitops_repo_url
19:       GIT_REPO_USERNAME = self.triggers.gitops_repo_username
20:       GIT_REPO_EMAIL    = self.triggers.gitops_repo_email
21:       GITHUB_TOKEN      = data.github_app_token.this.token
22:       CLUSTER_NAME      = self.triggers.cluster_name
23:       ENV               = self.triggers.environment
24:     }
Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or …
```
=> fix: Github Token passthrough on terraform

aws/eks-customer/README.md, aws/eks-customer/irsa.tf, aws/eks-customer/variables.tf
Fix proper IRSA namespace service account relation since `name` var is not always the namespace that the app is deployed
```release-note
```
=> feat: Fix proper namespace usage for IRSA

aws/eks-customer/README.md, aws/elrond/README.md, aws/elrond/elrond-db.tf, aws/elrond/variables.tf
Password elrond from AWS secrets
https://mattermost.atlassian.net/browse/CLD-8856
```release-note
NONE
```
=> Password elrond from AWS secrets

aws/cluster/README.md, aws/cluster/calico.tf, aws/cluster/eks_addon.tf, aws/cluster/manifests/calico_installation.yaml, aws/cluster/variables.tf, aws/cluster/worker_asg.tf, aws/eks-managed-node-groups/README.md, aws/eks-managed-node-groups/graviton_node_groups.tf, aws/eks-managed-node-groups/variables.tf
Create other ASG for calico
```release-note
NONE
```
=> Create other ASG for calico

aws/eks-customer/README.md, aws/eks-customer/scripts/deploy-utility.sh, aws/eks-customer/scripts/utils.sh, aws/eks-customer/utility.tf, aws/eks-customer/variables.tf
Optionally we can make PR instead of commit utilities directly to main. This is a safeguard especially for production environment.
Fix https://mattermost.atlassian.net/browse/CLD-8964
```release-note
eks-customer add option to make a PR for utilities deploy
```
=> CLD-8964: Make PR instead of commit utilities to main

.github/workflows/ci.yaml
Migrate tag-based references to commit SHA-based references for github workflows
https://mattermost.atlassian.net/browse/CLD-9005
=> migrate tag-based references to commit SHA-based references for github workflows

aws/eks-customer/README.md, aws/eks-customer/scripts/pgbouncer-initial-setup.yaml, aws/eks-customer/utility-utils.tf
This change will add an initial setup for pgBouncer. It will run once during cluster creation, removing pgBouncer configs from Argocd. After cluster creation, the provisioner will handle the pgBouncer configurations.
https://mattermost.atlassian.net/browse/CLD-9026
```release-note
Add initial setup for pgbouncer in eks-customer module
```
=> CLD-9026: add initial setup for pgbouncer

aws/cloud-lambda-storage/README.md, aws/cloud-lambda-storage/iam.tf
Add roles for lambda upload to substitute legacy user resources
https://mattermost.atlassian.net/browse/CLD-9143
```release-note
NONE
```
=> Add roles for lambda upload to substitute legacy user resources

aws/iam-custom-resources/github.tf
Remove thumbprint_list
Reasoning: For certain OIDC identity providers (e.g., Auth0, GitHub, GitLab, Google, or those using an Amazon S3-hosted JWKS endpoint), AWS relies on its own library of trusted root certificate authorities (CAs) for validation instead of using any configured thumbprints. In these cases, any configured thumbprint_list is retained in the configuration but not used for verification. For other IdPs, if no thumbprint_list is provided, IAM automatically retrieves and uses the top intermediate CA thumbprint from the OIDC IdP server certificate. However, if a thumbprint_list is initially configured and later removed, Terraform does not prompt IAM to retrieve a thumbprint the same way. Instead, it continues using the original thumbprint list from the initial configuration. …
=> Remove thumbprint_list

aws/eks-customer/README.md, aws/eks-customer/data.tf, aws/eks-customer/eks_managed_node-group.tf, aws/eks-customer/launch_template.tf, aws/eks-customer/variables.tf
In this PR we'll handle the launch template outside the `eks-managed-node-group` module passing the launch template values to it. This guarantees a smooth rollout process, triggering EKS node group updates when changes are applied.
https://mattermost.atlassian.net/browse/CLD-9174
```release-note
[eks-customer]: Handle launch templates outside eks-managed-node-group module
```
=> [CLD-9174] handle launch template outside the managed node group module

aws/eks-customer/README.md, aws/eks-customer/launch_template.tf, aws/eks-customer/variables.tf
Ability to set disk Iops and throughput per node group
https://mattermost.atlassian.net/browse/CLD-9287
```release-note
eks-customer Ability to set disk IOPS and throughput per node group
```
=> Ability to set disk parameters per node group

aws/cluster/README.md, aws/cluster/locals.tf, aws/eks-customer/launch_template.tf, aws/eks-managed-node-groups/graviton_node_groups.tf, aws/eks-managed-node-groups/node_groups.tf
Replace the pause config directly in the containerd config instead of using nodeConfig. We're experiencing sandbox change and pods getting restarted. Using the nodeConfig, it keeps the default config in the `config.toml` and adds the new one in the conf.d folder.
```
Normal   SandboxChanged  16s (x2 over 26s)  kubelet            Pod sandbox changed, it will be killed and re-created.
```
git checkout -b CLD-9467-fix-pause-image-address-for-al-2023
```release-note
NONE
```
=> Fix userdata to add pause container image
